import StructuralExhaustion.Graph.MinimumDegreeCycle

namespace Erdos64EG.Internal

open StructuralExhaustion
open StructuralExhaustion.Graph

universe u

/-!
The official statement quantifies over a Mathlib `SimpleGraph` and supplies
typeclass-based finite data.  The exact CT machines additionally need a
declared inspection order.  `Object` therefore pairs the same mathematical
graph with the framework's explicit `FiniteInput`; it does not introduce a
second graph representation.
-/

/-- A cycle length accepted by the official Erdős 64 conclusion.

The exponent is represented by a finite search space whose completeness is
proved below.  This makes the predicate directly executable without changing
its mathematical meaning.
-/
def PowerOfTwoLength (length : Nat) : Prop :=
  ∃ exponent : Fin (length + 1),
    2 ≤ exponent.1 ∧ length = 2 ^ exponent.1

instance powerOfTwoLengthDecidable (length : Nat) :
    Decidable (PowerOfTwoLength length) := by
  unfold PowerOfTwoLength
  infer_instance

private theorem exponent_le_two_pow (exponent : Nat) :
    exponent ≤ 2 ^ exponent := by
  induction exponent with
  | zero => simp
  | succ exponent inductionHypothesis =>
      rw [pow_succ]
      have positive : 0 < 2 ^ exponent := pow_pos (by decide) exponent
      omega

/-- The bounded executable predicate is exactly the unbounded predicate in
the official source. -/
theorem powerOfTwoLength_iff (length : Nat) :
    PowerOfTwoLength length ↔
      ∃ exponent : Nat, 2 ≤ exponent ∧ length = 2 ^ exponent := by
  constructor
  · rintro ⟨exponent, lower, equality⟩
    exact ⟨exponent.1, lower, equality⟩
  · rintro ⟨exponent, lower, equality⟩
    have bound : exponent < length + 1 := by
      rw [equality]
      exact Nat.lt_succ_of_le (exponent_le_two_pow exponent)
    exact ⟨⟨exponent, bound⟩, lower, equality⟩

/-- EG's entire problem-specific CT API: one threshold, one length predicate,
and its decision procedure.  Problems, searches, reductions, and closure
proofs are generated by the framework graph profile. -/
def staticInput (V : Type u) :
    MinimumDegreeCycle.StaticInput V (fun _object => Unit) where
  minimumDegree := 3
  LengthOK := PowerOfTwoLength

abbrev Object (V : Type u) := FiniteObject V
abbrev problem (V : Type u) := (staticInput V).problem
abbrev Baseline {V : Type u} := (staticInput V).problem.Baseline
abbrev Target {V : Type u} := (staticInput V).Target

/-- Convert the ordinary unbounded exponent formulation into the executable
bounded target predicate used by the internal framework boundary. -/
theorem target_of_unboundedPowerOfTwoCycle {V : Type u}
    (object : Object V)
    (cycle : HasCycleWithLength object.graph (fun length =>
      ∃ exponent : Nat, 2 ≤ exponent ∧ length = 2 ^ exponent)) :
    Target object := by
  rcases cycle with ⟨certificate⟩
  exact ⟨{
    vertex := certificate.vertex
    walk := certificate.walk
    isCycle := certificate.isCycle
    length_ok :=
      (powerOfTwoLength_iff certificate.walk.length).mpr
        certificate.length_ok
  }⟩

/-- The internal target is definitionally faithful to the exact conclusion
of the pinned official formulation. -/
theorem target_iff_official_conclusion {V : Type u} (object : Object V) :
    Target object ↔
      ∃ (exponent : Nat) (vertex : V)
        (cycle : object.graph.Walk vertex vertex),
        exponent ≥ 2 ∧ cycle.IsCycle ∧
          cycle.length = 2 ^ exponent := by
  constructor
  · rintro ⟨certificate⟩
    obtain ⟨exponent, lower, lengthEq⟩ :=
      (powerOfTwoLength_iff certificate.walk.length).mp
        certificate.length_ok
    exact ⟨exponent, certificate.vertex, certificate.walk,
      lower, certificate.isCycle, lengthEq⟩
  · rintro ⟨exponent, vertex, cycle, lower, isCycle, lengthEq⟩
    exact ⟨{
      vertex := vertex
      walk := cycle
      isCycle := isCycle
      length_ok := (powerOfTwoLength_iff cycle.length).mpr
        ⟨exponent, lower, lengthEq⟩
    }⟩

end Erdos64EG.Internal
