import Erdos64EG.P13WeightedColdRestrictedComponentSchedule

namespace Erdos64EG.Internal

#check StructuralExhaustion.Graph.OrderedBFSTree.Profile.DeclaredOrderShortestPath
#check StructuralExhaustion.Graph.InducedPathRestrictedComponentBoundarySchedule.componentPathDeclaredOrderCertificate
#check restricted_component_payload
#check restricted_component_declaredOrderCorridor
#check p13RestrictedLexFirstCorridorProfile
#check p13RestrictedLexFirstCorridor
#check restricted_component_lexFirstCorridor

#print axioms restricted_component_declaredOrderCorridor
#print axioms restricted_component_lexFirstCorridor

end Erdos64EG.Internal
