import Erdos64EG.P13WeightedColdRestrictedF2Handoff

namespace Erdos64EG.Internal

#check P13WeightedColdRestrictedPrefixPackage.StageF2.targetDefectSource
#check P13WeightedColdRestrictedPrefixPackage.StageF2.routeTargetDefect
#check P13WeightedColdRestrictedPrefixPackage.StageF2.routed_left
#check P13WeightedColdRestrictedPrefixPackage.StageF2.routed_right
#check P13WeightedColdRestrictedPrefixPackage.StageF2.routed_outside
#check P13WeightedColdRestrictedPrefixPackage.StageF2.routed_targetDefective
#check P13WeightedColdRestrictedPrefixPackage.StageF2.routed_ambient_preserved

#print axioms P13WeightedColdRestrictedPrefixPackage.StageF2.routed_targetDefective
#print axioms P13WeightedColdRestrictedPrefixPackage.StageF2.routed_ambient_preserved

end Erdos64EG.Internal
