import StructuralExhaustion.CT1.Theorems
import StructuralExhaustion.Core.EnumerationCombinators

namespace StructuralExhaustion.CT1

universe uAmbient uBranch uCode

/-!
Reusable CT1 adapter for the common single-code target pattern.

An application describes only its public target, a finite code enumerator,
the decidable acceptance predicate, and the semantic encode/decode maps.  The
framework generates the CT1 specification, executable capability, and exact
public-target bridge.
-/

/-- A proof-carrying encoding of a public target.  This interface has no
witness enumeration: successful execution receives one explicit accepted
code and follows the typed CT1 path directly. -/
structure TargetCertificateEncoding
    {P : Core.Problem.{uAmbient, uBranch}}
    (PublicTarget : P.Ambient → Prop) where
  Code : P.Ambient → Type uCode
  Accepts : (G : P.Ambient) → Code G → Prop
  encode : ∀ {G : P.Ambient}, PublicTarget G → ∃ code, Accepts G code
  decode : ∀ {G : P.Ambient} {code : Code G}, Accepts G code → PublicTarget G

namespace TargetCertificateEncoding

def spec {P : Core.Problem.{uAmbient, uBranch}}
    {PublicTarget : P.Ambient → Prop}
    (encoding : TargetCertificateEncoding.{uAmbient, uBranch, uCode}
      PublicTarget) : Spec P where
  TestIndex := Unit
  Witness := fun G _ => encoding.Code G
  Realizes := fun G _ code => encoding.Accepts G code

def bridge {P : Core.Problem.{uAmbient, uBranch}}
    {PublicTarget : P.Ambient → Prop}
    (encoding : TargetCertificateEncoding.{uAmbient, uBranch, uCode}
      PublicTarget) : TargetBridge encoding.spec PublicTarget where
  equivalent := fun G => by
    constructor
    · intro publicTarget
      rcases encoding.encode publicTarget with ⟨code, accepts⟩
      exact ⟨(), code, accepts⟩
    · rintro ⟨index, code, accepts⟩
      cases index
      exact encoding.decode accepts

/-- Execute CT1 from one explicit accepted code. -/
def run {P : Core.Problem.{uAmbient, uBranch}}
    {PublicTarget : P.Ambient → Prop}
    (encoding : TargetCertificateEncoding.{uAmbient, uBranch, uCode}
      PublicTarget)
    (input : Input P) (code : encoding.Code input.context.G)
    (accepts : encoding.Accepts input.context.G code) :
    CertifiedC1Run encoding.spec input :=
  runC1OfRealization encoding.spec input () code accepts

/-- Execute the typed avoiding path from a proof that the public target is
absent.  This is the negative counterpart of certificate-driven `run`; it
does not materialize or scan the target-code universe. -/
def runAvoiding {P : Core.Problem.{uAmbient, uBranch}}
    {PublicTarget : P.Ambient → Prop}
    (encoding : TargetCertificateEncoding.{uAmbient, uBranch, uCode}
      PublicTarget)
    (input : Input P) (avoids : ¬ PublicTarget input.context.G) :
    CertifiedAvoidingRun encoding.spec input :=
  runAvoidingOfNoRealization encoding.spec input <| by
    intro index code accepts
    cases index
    exact avoids (encoding.decode accepts)

theorem publicTarget_of_run {P : Core.Problem.{uAmbient, uBranch}}
    {PublicTarget : P.Ambient → Prop}
    (encoding : TargetCertificateEncoding.{uAmbient, uBranch, uCode}
      PublicTarget)
    (input : Input P) (code : encoding.Code input.context.G)
    (accepts : encoding.Accepts input.context.G code) :
    PublicTarget input.context.G :=
  encoding.decode accepts

theorem not_publicTarget_of_runAvoiding
    {P : Core.Problem.{uAmbient, uBranch}}
    {PublicTarget : P.Ambient → Prop}
    (encoding : TargetCertificateEncoding.{uAmbient, uBranch, uCode}
      PublicTarget)
    (input : Input P) (avoids : ¬ PublicTarget input.context.G) :
    ¬ PublicTarget input.context.G :=
  encoding.bridge.not_publicTarget_of_not_target
    (encoding.runAvoiding input avoids).result.verified

end TargetCertificateEncoding

/-- A finite executable encoding of a public mathematical target. -/
structure TargetEncoding
    {P : Core.Problem.{uAmbient, uBranch}}
    (PublicTarget : P.Ambient → Prop) where
  Code : P.Ambient → Type uCode
  codes : (G : P.Ambient) → FinEnum (Code G)
  Accepts : (G : P.Ambient) → Code G → Prop
  acceptsDecidable :
    (G : P.Ambient) → (code : Code G) → Decidable (Accepts G code)
  inputSize : P.Ambient → Nat
  workCoefficient : Nat
  workDegree : Nat
  workBound : ∀ G,
    (codes G).orderedValues.length ≤
      workCoefficient * (inputSize G + 1) ^ workDegree
  encode : ∀ {G : P.Ambient}, PublicTarget G → ∃ code, Accepts G code
  decode : ∀ {G : P.Ambient} {code : Code G}, Accepts G code → PublicTarget G

namespace TargetEncoding

/-- The canonical one-test CT1 specification generated by an encoding. -/
def spec {P : Core.Problem.{uAmbient, uBranch}}
    {PublicTarget : P.Ambient → Prop}
    (encoding : TargetEncoding.{uAmbient, uBranch, uCode} PublicTarget) :
    Spec P where
  TestIndex := Unit
  Witness := fun G _ => encoding.Code G
  Realizes := fun G _ code => encoding.Accepts G code

/-- The complete executable CT1 capability generated by an encoding. -/
def capability {P : Core.Problem.{uAmbient, uBranch}}
    {PublicTarget : P.Ambient → Prop}
    (encoding : TargetEncoding.{uAmbient, uBranch, uCode} PublicTarget) :
    Capability encoding.spec where
  tests := Core.Enumeration.unit
  witnesses := fun G _ => encoding.codes G
  realizesDecidable := fun G _ code => encoding.acceptsDecidable G code
  inputSize := encoding.inputSize
  workCoefficient := encoding.workCoefficient
  workDegree := encoding.workDegree
  workBound := fun G => by
    change
      (Core.Enumeration.unit.orderedValues.map fun _ : Unit =>
        (encoding.codes G).orderedValues.length).sum ≤ _
    rw [show Core.Enumeration.unit.orderedValues = [()] from rfl]
    simpa using encoding.workBound G

/-- The target equivalence generated by the encoding and decoding maps. -/
def bridge {P : Core.Problem.{uAmbient, uBranch}}
    {PublicTarget : P.Ambient → Prop}
    (encoding : TargetEncoding.{uAmbient, uBranch, uCode} PublicTarget) :
    TargetBridge encoding.spec PublicTarget where
  equivalent := fun G => by
    constructor
    · intro publicTarget
      rcases encoding.encode publicTarget with ⟨code, accepts⟩
      exact ⟨(), code, accepts⟩
    · rintro ⟨index, code, accepts⟩
      cases index
      exact encoding.decode accepts

end TargetEncoding

end StructuralExhaustion.CT1
