import Hypostructure.Core.Prelude

/-!
# Provision boundary

This module records where declarations enter an executable proof.  Primitive
mathematics supplied by a domain or theorem application and values generated
by Hypostructure have distinct types; metadata therefore cannot silently
relabel a generated decision or residual as an author input.
-/

namespace Hypostructure.Core

/-- A source-oriented reference to a Lean declaration.  It is audit metadata,
not a runtime reflection mechanism. -/
structure DeclarationRef where
  moduleName : String
  declarationName : String
  deriving Repr, DecidableEq

namespace DeclarationRef

/-- Stable qualified spelling used by exporters. -/
def qualifiedName (reference : DeclarationRef) : String :=
  reference.moduleName ++ "." ++ reference.declarationName

end DeclarationRef

/-- Kinds of primitive mathematics that an application or domain profile may
provide.  None of these roles denotes a selected branch or a successor. -/
inductive PrimitiveRole where
  | definition
  | operator
  | finiteEnumeration
  | decisionProcedure
  | semanticLaw
  | localCertificate
  | importedContract
  deriving Repr, DecidableEq

/-- One explicitly author-supplied primitive declaration. -/
structure AuthorPrimitiveRef where
  source : DeclarationRef
  role : PrimitiveRole
  deriving Repr, DecidableEq

/-- How Core obtains a dependency that is not supplied as primitive
mathematics by the current application node. -/
inductive InferenceRole where
  | typeclassResolution
  | definitionalReduction
  | predecessorProjection
  | registeredProfile
  deriving Repr, DecidableEq

/-- One dependency inferred by the framework or read from the predecessor. -/
structure InferredDependencyRef where
  source : DeclarationRef
  role : InferenceRole
  deriving Repr, DecidableEq

/-- Kinds of values that only framework execution is allowed to emit. -/
inductive GeneratedRole where
  | searchResult
  | typedOutcome
  | executionTrace
  | residualStage
  | transitionResult
  | closureResult
  | auditRecord
  deriving Repr, DecidableEq

/-- One declaration generated by reusable framework machinery. -/
structure FrameworkOutputRef where
  source : DeclarationRef
  role : GeneratedRole
  deriving Repr, DecidableEq

namespace Provision

/-- The author boundary and generated boundary are intentionally represented
by separate sum constructors when a combined audit stream is required. -/
inductive Entry where
  | primitive (input : AuthorPrimitiveRef)
  | inferred (dependency : InferredDependencyRef)
  | generated (output : FrameworkOutputRef)
  deriving Repr, DecidableEq

/-- Whether an audit entry is primitive mathematics supplied by the author. -/
def Entry.isAuthorPrimitive : Entry -> Bool
  | .primitive _ => true
  | .inferred _ | .generated _ => false

/-- Whether an audit entry is an output of framework execution. -/
def Entry.isFrameworkOutput : Entry -> Bool
  | .generated _ => true
  | .primitive _ | .inferred _ => false

theorem Entry.authorPrimitive_not_frameworkOutput
    (entry : Entry) (author : entry.isAuthorPrimitive = true) :
    entry.isFrameworkOutput = false := by
  cases entry <;> simp_all [isAuthorPrimitive, isFrameworkOutput]

end Provision

end Hypostructure.Core
