import Hypostructure.CT17.Search

/-!
# CT17 accumulated execution

The complete CT17 machine appends one private routed payload to the literal
predecessor.  Applications cannot choose a terminal, pair unrelated evidence
with a trace, or replace the retained predecessor.
-/

namespace Hypostructure.CT17

universe uPrevious uTarget uOffset uPosition uValue

variable {Previous : Type uPrevious}
  {spec : Spec.{uPrevious, uTarget, uOffset, uPosition, uValue} Previous}

/-- Exhaustive semantic terminals of bounded target thickening. -/
inductive Terminal where
  | incompatibility
  | exhausted
  | survivors
  | targetHit
  | orbit
  deriving DecidableEq, Repr

/-- Audit nodes in the canonical CT17 control flow. -/
inductive NodeId where
  | entry
  | inheritedSchedules
  | admissibilityScan
  | scaleDecision
  | survivorEnumeration
  | survivorDecision
  | orbitArithmetic
  | incompatibilityTerminal
  | exhaustedTerminal
  | survivorTerminal
  | targetHitTerminal
  | orbitTerminal
  deriving DecidableEq, Repr

/-- Terminal-indexed evidence generated by the framework. -/
inductive Outcome (capability : Capability spec) (previous : Previous) :
    Terminal -> Type _ where
  | incompatibility
      (residual : IncompatibilityResidual capability previous) :
      Outcome capability previous .incompatibility
  | exhausted
      (compatible : CompatibleState capability previous)
      (finite : FiniteScaleState capability previous)
      (certificate : ExhaustedCertificate capability previous) :
      Outcome capability previous .exhausted
  | survivors
      (compatible : CompatibleState capability previous)
      (finite : FiniteScaleState capability previous)
      (residual : SurvivorResidual capability previous) :
      Outcome capability previous .survivors
  | targetHit
      (compatible : CompatibleState capability previous)
      (orbitScale : OrbitScaleState capability previous)
      (certificate : TargetHitCertificate capability previous) :
      Outcome capability previous .targetHit
  | orbit
      (compatible : CompatibleState capability previous)
      (orbitScale : OrbitScaleState capability previous)
      (residual : OrbitResidual capability previous) :
      Outcome capability previous .orbit

/-- Trace indexed by its semantic terminal. -/
inductive Trace : Terminal -> Type where
  | incompatibility : Trace .incompatibility
  | exhausted : Trace .exhausted
  | survivors : Trace .survivors
  | targetHit : Trace .targetHit
  | orbit : Trace .orbit

namespace Trace

/-- Observable nodes of a typed trace. -/
def nodes : {terminal : Terminal} -> Trace terminal -> List NodeId
  | .incompatibility, .incompatibility =>
      [.entry, .inheritedSchedules, .admissibilityScan,
        .incompatibilityTerminal]
  | .exhausted, .exhausted =>
      [.entry, .inheritedSchedules, .admissibilityScan, .scaleDecision,
        .survivorEnumeration, .survivorDecision, .exhaustedTerminal]
  | .survivors, .survivors =>
      [.entry, .inheritedSchedules, .admissibilityScan, .scaleDecision,
        .survivorEnumeration, .survivorDecision, .survivorTerminal]
  | .targetHit, .targetHit =>
      [.entry, .inheritedSchedules, .admissibilityScan, .scaleDecision,
        .orbitArithmetic, .targetHitTerminal]
  | .orbit, .orbit =>
      [.entry, .inheritedSchedules, .admissibilityScan, .scaleDecision,
        .orbitArithmetic, .orbitTerminal]

/-- Canonical node sequence fixed by each terminal. -/
def expectedNodes : Terminal -> List NodeId
  | .incompatibility =>
      [.entry, .inheritedSchedules, .admissibilityScan,
        .incompatibilityTerminal]
  | .exhausted =>
      [.entry, .inheritedSchedules, .admissibilityScan, .scaleDecision,
        .survivorEnumeration, .survivorDecision, .exhaustedTerminal]
  | .survivors =>
      [.entry, .inheritedSchedules, .admissibilityScan, .scaleDecision,
        .survivorEnumeration, .survivorDecision, .survivorTerminal]
  | .targetHit =>
      [.entry, .inheritedSchedules, .admissibilityScan, .scaleDecision,
        .orbitArithmetic, .targetHitTerminal]
  | .orbit =>
      [.entry, .inheritedSchedules, .admissibilityScan, .scaleDecision,
        .orbitArithmetic, .orbitTerminal]

theorem nodes_eq_expected : {terminal : Terminal} ->
    (trace : Trace terminal) -> trace.nodes = expectedNodes terminal
  | .incompatibility, .incompatibility => rfl
  | .exhausted, .exhausted => rfl
  | .survivors, .survivors => rfl
  | .targetHit, .targetHit => rfl
  | .orbit, .orbit => rfl

end Trace

/-- Private framework route selected by the canonical scans and Core
decisions.  It retains the exact initial compatibility execution for visible
work accounting. -/
structure Routed (capability : Capability spec) (previous : Previous) where
  private mk ::
  admissibilityExecution : Core.Finite.Search.Execution
    (capability.pairScheduleAt previous)
    (Incompatible (spec := spec) previous)
  admissibilityExecution_eq : admissibilityExecution =
    admissibilityScan capability previous
  terminal : Terminal
  outcome : Outcome capability previous terminal

/-- Execute every internal search and decision without changing the incoming
ledger. -/
def routeReference (capability : Capability spec) (previous : Previous) :
    Routed capability previous :=
  let admissibility := routeAdmissibility capability previous
  match admissibility.added with
  | .yesBranch hasFailure =>
      .mk admissibility.previous rfl .incompatibility
        (.incompatibility
          (admissibility.previous.hitOfHasHit hasFailure))
  | .noBranch compatible =>
      let scale := routeScale capability previous compatible
      match scale.added with
      | .yesBranch finite =>
          let enumeration := enumerateSurvivors capability previous
          let survivors := routeSurvivors capability previous enumeration
          match survivors.added with
          | .yesBranch nonempty =>
              .mk admissibility.previous rfl .survivors
                (.survivors compatible finite
                  (SurvivorResidual.ofNonempty survivors.previous nonempty))
          | .noBranch exhausted =>
              .mk admissibility.previous rfl .exhausted
                (.exhausted compatible finite
                  (ExhaustedCertificate.ofExhaustion survivors.previous
                    exhausted))
      | .noBranch orbitScale =>
          let arithmetic := routeArithmetic capability previous
          match arithmetic.added with
          | .yesBranch hasHit =>
              .mk admissibility.previous rfl .targetHit
                (.targetHit compatible orbitScale
                  (arithmetic.previous.hitOfHasHit hasHit))
          | .noBranch avoids =>
              .mk admissibility.previous rfl .orbit
                (.orbit compatible orbitScale
                  (OrbitResidual.ofAvoidance avoids))

/-- Unique typed trace selected from generated outcome evidence. -/
def traceOfOutcome {capability : Capability spec} {previous : Previous}
    {terminal : Terminal} (outcome : Outcome capability previous terminal) :
    Trace terminal := by
  cases outcome with
  | incompatibility _ => exact .incompatibility
  | exhausted _ _ _ => exact .exhausted
  | survivors _ _ _ => exact .survivors
  | targetHit _ _ _ => exact .targetHit
  | orbit _ _ _ => exact .orbit

/-- Unique typed trace selected by a private route. -/
def traceOfRouted {capability : Capability spec} {previous : Previous}
    (routed : Routed capability previous) : Trace routed.terminal :=
  traceOfOutcome routed.outcome

/-- Exact visible checks for each generated route.

Compatibility and target scans use their actual first-hit prefix lengths.
Finite branches retain the sum of actual nested block scans.  Orbit avoidance
also charges one value computation per inherited offset when materializing the
residual ledger.
-/
def outcomeChecks {capability : Capability spec} {previous : Previous}
    (admissibilityExecution : Core.Finite.Search.Execution
      (capability.pairScheduleAt previous)
      (Incompatible (spec := spec) previous)) :
    {terminal : Terminal} -> Outcome capability previous terminal -> Nat
  | .incompatibility, .incompatibility _ =>
      Core.Finite.Accounting.executionChecks admissibilityExecution
  | .exhausted, .exhausted _ _ certificate =>
      Core.Finite.Accounting.executionChecks admissibilityExecution + 1 +
        certificate.enumeration.checks + 1
  | .survivors, .survivors _ _ residual =>
      Core.Finite.Accounting.executionChecks admissibilityExecution + 1 +
        residual.enumeration.checks + 1
  | .targetHit, .targetHit _ _ certificate =>
      Core.Finite.Accounting.executionChecks admissibilityExecution + 1 +
        certificate.index.1 + 1
  | .orbit, .orbit _ _ _ =>
      Core.Finite.Accounting.executionChecks admissibilityExecution + 1 +
        (capability.pairScheduleAt previous).card +
        (capability.offsetsAt previous).card

/-- Every exact branch count is bounded by the complete prescribed CT17
schedule. -/
theorem outcomeChecks_le_limit {capability : Capability spec}
    {previous : Previous} {terminal : Terminal}
    (admissibilityExecution : Core.Finite.Search.Execution
      (capability.pairScheduleAt previous)
      (Incompatible (spec := spec) previous))
    (outcome : Outcome capability previous terminal) :
    outcomeChecks admissibilityExecution outcome <=
      localCheckBound (capability.targetsAt previous)
        (capability.offsetsAt previous)
        (capability.positionsAt previous) := by
  have compatibilityBound :
      Core.Finite.Accounting.executionChecks admissibilityExecution <=
        (capability.pairScheduleAt previous).card :=
    Core.Finite.Accounting.executionChecks_le_card admissibilityExecution
  have pairCard : (capability.pairScheduleAt previous).card =
      (capability.targetsAt previous).card *
        (capability.offsetsAt previous).card :=
    Core.Finite.Enumeration.card_product _ _
  cases outcome with
  | incompatibility _ =>
      simp only [outcomeChecks, localCheckBound]
      rw [pairCard] at compatibilityBound
      omega
  | exhausted _ _ certificate =>
      have survivorBound := certificate.enumeration.checks_le_product
      simp only [outcomeChecks, localCheckBound]
      rw [pairCard] at compatibilityBound survivorBound
      omega
  | survivors _ _ residual =>
      have survivorBound := residual.enumeration.checks_le_product
      simp only [outcomeChecks, localCheckBound]
      rw [pairCard] at compatibilityBound survivorBound
      omega
  | targetHit _ _ certificate =>
      have arithmeticBound : certificate.index.1 + 1 <=
          (capability.pairScheduleAt previous).card :=
        Nat.succ_le_iff.mpr certificate.index.isLt
      have arithmeticBound' : certificate.index.1 + 1 <=
          (capability.targetsAt previous).card *
            (capability.offsetsAt previous).card :=
        arithmeticBound.trans_eq pairCard
      simp only [outcomeChecks, localCheckBound]
      rw [pairCard] at compatibilityBound
      omega
  | orbit _ _ _ =>
      simp only [outcomeChecks, localCheckBound]
      rw [pairCard] at compatibilityBound
      rw [pairCard]
      omega

/-- One CT17 execution is one extension of the literal predecessor. -/
abbrev Stage
    (spec : Spec.{uPrevious, uTarget, uOffset, uPosition, uValue} Previous)
    (capability : Capability spec) :=
  Core.Residual.Ledger.Extension Previous fun previous =>
    Routed capability previous

/-- Closed public CT17 execution result. -/
structure ExecutionResult
    (spec : Spec.{uPrevious, uTarget, uOffset, uPosition, uValue} Previous)
    (capability : Capability spec) where
  private mk ::
  stage : Stage spec capability
  trace : Trace stage.added.terminal
  checks : Nat
  checks_eq : checks = outcomeChecks stage.added.admissibilityExecution
    stage.added.outcome

namespace ExecutionResult

/-- Terminal derived from the retained private route. -/
def terminal {capability : Capability spec}
    (result : ExecutionResult spec capability) : Terminal :=
  result.stage.added.terminal

/-- Exact terminal-indexed generated evidence. -/
def outcome {capability : Capability spec}
    (result : ExecutionResult spec capability) :
    Outcome capability result.stage.previous result.terminal :=
  result.stage.added.outcome

/-- Observable exact trace. -/
def traceNodes {capability : Capability spec}
    (result : ExecutionResult spec capability) : List NodeId :=
  result.trace.nodes

/-- Branch-exact work never exceeds the complete local schedule. -/
theorem checks_le_limit {capability : Capability spec}
    (result : ExecutionResult spec capability) :
    result.checks <= localCheckBound
      (capability.targetsAt result.stage.previous)
      (capability.offsetsAt result.stage.previous)
      (capability.positionsAt result.stage.previous) := by
  rw [result.checks_eq]
  exact outcomeChecks_le_limit result.stage.added.admissibilityExecution
    result.stage.added.outcome

/-- Every execution satisfies the registered polynomial envelope. -/
theorem checks_le_polynomial {capability : Capability spec}
    (result : ExecutionResult spec capability) :
    result.checks <= capability.workCoefficient *
      (capability.inputSize result.stage.previous + 1) ^
        capability.workDegree :=
  result.checks_le_limit.trans (capability.workBound result.stage.previous)

end ExecutionResult

/-- Execute CT17 on one literal incoming ledger. -/
def run
    (spec : Spec.{uPrevious, uTarget, uOffset, uPosition, uValue} Previous)
    (capability : Capability spec) (previous : Previous) :
    ExecutionResult spec capability :=
  let routed := routeReference capability previous
  {
    stage := Core.Residual.Ledger.extend previous routed
    trace := traceOfRouted routed
    checks := outcomeChecks routed.admissibilityExecution routed.outcome
    checks_eq := rfl
  }

@[simp] theorem run_previous
    (spec : Spec.{uPrevious, uTarget, uOffset, uPosition, uValue} Previous)
    (capability : Capability spec) (previous : Previous) :
    (run spec capability previous).stage.previous = previous :=
  rfl

end Hypostructure.CT17
