import EvenCycleExample.Problem

namespace EvenCycleExample

open StructuralExhaustion

universe u

/-!
CT1 is entirely generated by the reusable graph cycle-target adapter.  The
example contributes only the even-length predicate.
-/

abbrev evenCycleEncoding (V : Type u) := (staticInput V).targetEncoding

abbrev ct1Spec (V : Type u) := (staticInput V).ct1Spec

abbrev ct1TargetBridge (V : Type u) := (staticInput V).ct1TargetBridge

end EvenCycleExample
