import StructuralExhaustion.CT4.Automation
import StructuralExhaustion.CT12.Automation
import StructuralExhaustion.Graph.Coloring
import StructuralExhaustion.Graph.EliminationOrder

namespace StructuralExhaustion.Graph.GreedyColoring

open StructuralExhaustion

universe u

open EliminationOrder

/-- The canonical later-neighbour represented by a CT4 payer index. -/
def payerVertex (object : FiniteObject V) (vertex : V) (tail : List V)
    (payer : Fin (laterNeighbors object vertex tail).length) : V :=
  (laterNeighbors object vertex tail)[payer.1]

/-- Minimal CT4 functional-cardinality profile for choosing a color not used
by later neighbours.  CT4 supplies all irrelevant charging fields and the
complete missing-demand execution. -/
def stepProfile (object : FiniteObject V) (bound : Nat)
    (vertex : V) (tail : List V)
    (tailColoring : Coloring.Partial object (bound + 1)
      (verticesFinset object tail)) :
    CT4.FunctionalCardinalityProfile (Coloring.problem V) where
  Demand := Fin (bound + 1)
  Payer := Fin (laterNeighbors object vertex tail).length
  Eligible := fun _context color payer =>
    tailColoring.color (payerVertex object vertex tail payer) = color
  demands := inferInstance
  payers := inferInstance
  eligibleDecidable := fun _context color payer => inferInstance
  functional := by
    intro _context payer color₁ color₂ first second
    exact first.symm.trans second

/-- CT4 specification generated by the minimal step profile. -/
abbrev stepSpec (object : FiniteObject V) (bound : Nat)
    (vertex : V) (tail : List V)
    (tailColoring : Coloring.Partial object (bound + 1)
      (verticesFinset object tail)) :=
  (stepProfile object bound vertex tail tailColoring).spec

/-- CT4 capability generated by the minimal step profile. -/
abbrev stepCapability (object : FiniteObject V) (bound : Nat)
    (vertex : V) (tail : List V)
    (tailColoring : Coloring.Partial object (bound + 1)
      (verticesFinset object tail)) :=
  (stepProfile object bound vertex tail tailColoring).capability

/-- One neighbour slot cannot witness two different colors. -/
theorem step_functional (object : FiniteObject V) (bound : Nat)
    (vertex : V) (tail : List V)
    (tailColoring : Coloring.Partial object (bound + 1)
      (verticesFinset object tail)) :
    ∀ payer color₁ color₂,
      (stepSpec object bound vertex tail tailColoring).Eligible
          (Coloring.context object) color₁ payer →
      (stepSpec object bound vertex tail tailColoring).Eligible
          (Coloring.context object) color₂ payer →
      color₁ = color₂ := by
  exact (stepProfile object bound vertex tail tailColoring).functional
    (Coloring.context object)

/-- Exact CT4 execution for one coloring step. -/
def stepRun (object : FiniteObject V) (bound : Nat)
    (vertex : V) (tail : List V)
    (tailColoring : Coloring.Partial object (bound + 1)
      (verticesFinset object tail)) :=
  (stepProfile object bound vertex tail tailColoring).run
    (Coloring.context object)

/-- A bounded later-neighbour set forces the exact CT4 run to the
missing-payer terminal. -/
theorem step_terminal_missing (object : FiniteObject V) (bound : Nat)
    (vertex : V) (tail : List V)
    (tailColoring : Coloring.Partial object (bound + 1)
      (verticesFinset object tail))
    (headBound : (laterNeighbors object vertex tail).length ≤ bound) :
    (stepRun object bound vertex tail tailColoring).terminal = .missing := by
  apply CT4.FunctionalCardinalityProfile.run_terminal_eq_missing
  change FinEnum.card (Fin (laterNeighbors object vertex tail).length) <
    FinEnum.card (Fin (bound + 1))
  simpa using Nat.lt_succ_of_le headBound

/-- Missing-color evidence selected by the exact CT4 execution. -/
def stepResidual (object : FiniteObject V) (bound : Nat)
    (vertex : V) (tail : List V)
    (tailColoring : Coloring.Partial object (bound + 1)
      (verticesFinset object tail))
    (headBound : (laterNeighbors object vertex tail).length ≤ bound) :
    CT4.MissingPayerResidual
      (stepSpec object bound vertex tail tailColoring)
      (Coloring.context object) :=
  CT4.FunctionalCardinalityProfile.missingResidual
    (stepProfile object bound vertex tail tailColoring)
    (Coloring.context object)
    (by
      change FinEnum.card (Fin (laterNeighbors object vertex tail).length) <
        FinEnum.card (Fin (bound + 1))
      simpa using Nat.lt_succ_of_le headBound)

/-- Canonical first color unused by every later neighbour. -/
def selectedColor (object : FiniteObject V) (bound : Nat)
    (vertex : V) (tail : List V)
    (tailColoring : Coloring.Partial object (bound + 1)
      (verticesFinset object tail))
    (headBound : (laterNeighbors object vertex tail).length ≤ bound) :
    Fin (bound + 1) :=
  (stepResidual object bound vertex tail tailColoring headBound).demand

/-- CT4's missing-payer residual means that the selected color is absent
from every already-colored later neighbour. -/
theorem selectedColor_available (object : FiniteObject V) (bound : Nat)
    (vertex : V) (tail : List V)
    (tailColoring : Coloring.Partial object (bound + 1)
      (verticesFinset object tail))
    (headBound : (laterNeighbors object vertex tail).length ≤ bound) :
    ∀ neighbor, neighbor ∈ verticesFinset object tail →
      object.graph.Adj vertex neighbor →
      selectedColor object bound vertex tail tailColoring headBound ≠
        tailColoring.color neighbor := by
  intro neighbor neighborMember adjacent equal
  letI : DecidableEq V := object.input.vertices.decEq
  have neighborInTail : neighbor ∈ tail := by
    exact (mem_verticesFinset_iff object neighbor tail).1 neighborMember
  have neighborInLater : neighbor ∈ laterNeighbors object vertex tail :=
    (mem_laterNeighbors_iff object vertex neighbor tail).2
      ⟨neighborInTail, adjacent⟩
  let payer : Fin (laterNeighbors object vertex tail).length :=
    ⟨(laterNeighbors object vertex tail).idxOf neighbor,
      List.idxOf_lt_length_iff.mpr neighborInLater⟩
  have payerValue : payerVertex object vertex tail payer = neighbor := by
    exact List.getElem_idxOf (List.idxOf_lt_length_iff.mpr neighborInLater)
  have noEligible :=
    (stepResidual object bound vertex tail tailColoring headBound).noEligible payer
  apply noEligible
  change tailColoring.color (payerVertex object vertex tail payer) =
    selectedColor object bound vertex tail tailColoring headBound
  simpa [payerValue] using equal.symm

/-- Deterministic reverse fold along a certified elimination order. -/
def colorOrder (object : FiniteObject V) (bound : Nat) :
    (values : List V) → values.Nodup → BoundedOrder object bound values →
      Coloring.Partial object (bound + 1) (verticesFinset object values)
  | [], _nodup, .nil =>
      Coloring.Partial.empty object (bound + 1) (Nat.succ_pos bound)
  | vertex :: tail, nodup, .cons headBound tailBound => by
      letI : DecidableEq V := object.input.vertices.decEq
      let tailColoring := colorOrder object bound tail nodup.tail tailBound
      have fresh : vertex ∉ verticesFinset object tail := by
        rw [mem_verticesFinset_iff]
        exact (List.nodup_cons.mp nodup).1
      simpa [verticesFinset] using
        Coloring.Partial.insert object tailColoring vertex fresh
          (selectedColor object bound vertex tail tailColoring headBound)
          (selectedColor_available object bound vertex tail tailColoring headBound)

/-- Convert a complete certified elimination order into a Mathlib coloring. -/
def coloringOfOrder (object : FiniteObject V) (bound : Nat)
    (values : List V) (nodup : values.Nodup)
    (complete : ∀ vertex, vertex ∈ values)
    (bounded : BoundedOrder object bound values) :
    object.graph.Coloring (Fin (bound + 1)) := by
  letI : DecidableEq V := object.input.vertices.decEq
  exact Coloring.Partial.toColoring object
    (colorOrder object bound values nodup bounded)
    (fun vertex => by simpa using complete vertex)

/-- Generic degeneracy-style theorem for any explicitly certified bounded
elimination order. -/
theorem colorable_of_bounded_order (object : FiniteObject V) (bound : Nat)
    (values : List V) (nodup : values.Nodup)
    (complete : ∀ vertex, vertex ∈ values)
    (bounded : BoundedOrder object bound values) :
    object.graph.Colorable (bound + 1) :=
  ⟨coloringOfOrder object bound values nodup complete bounded⟩

/-- Canonical deterministic `(maxDegree + 1)` coloring in the object's
declared vertex order. -/
def maxDegreeColoring (object : FiniteObject V) :
    object.graph.Coloring (Fin (object.maxDegree + 1)) :=
  coloringOfOrder object object.maxDegree
    object.input.vertices.orderedValues
    object.input.vertices.nodup_orderedValues
    object.input.vertices.mem_orderedValues
    (BoundedOrder.of_degree_bound object object.maxDegree
      object.degree_le_maxDegree object.input.vertices.orderedValues
      object.input.vertices.nodup_orderedValues)

/-- The unconditional greedy-coloring theorem for a finite Mathlib graph. -/
theorem colorable_maxDegree_succ (object : FiniteObject V) :
    object.graph.Colorable (object.maxDegree + 1) :=
  ⟨maxDegreeColoring object⟩

/-- CT12 execution that certifies the exact vertex-peeling schedule used by
the greedy coloring fold. -/
def peelingRun (object : FiniteObject V) :=
  CT12.ListPeeling.run (Coloring.context object)
    object.input.vertices.orderedValues

theorem peeling_terminal_exhausted (object : FiniteObject V) :
    (peelingRun object).terminal = .exhausted :=
  CT12.ListPeeling.run_terminal_exhausted (Coloring.context object)
    object.input.vertices.orderedValues

/-! ## CT1 validation of the generated coloring -/

abbrev ct1Encoding (V : Type u) (colorCount : Nat) :=
  Coloring.targetEncoding V colorCount

def ct1Input (object : FiniteObject V) :
    CT1.Input (Coloring.problem V) where
  context := Coloring.context object

/-- Exact CT1 success run for the framework-generated greedy coloring. -/
def ct1Run (object : FiniteObject V) :=
  (ct1Encoding V (object.maxDegree + 1)).run (ct1Input object)
    (fun vertex => maxDegreeColoring object vertex)
    (fun _left _right adjacent => (maxDegreeColoring object).valid adjacent)

end StructuralExhaustion.Graph.GreedyColoring
