import Mathlib.Tactic
import StructuralExhaustion.Graph.CycleCertificate
import StructuralExhaustion.Graph.MinimumDegreeCycle

namespace StructuralExhaustion.Graph.HighCenterStructure

open StructuralExhaustion

universe u

/-- Exact length-four predicate used by the local CT1 audit. -/
def FourLength (length : Nat) : Prop := length = 4

instance (length : Nat) : Decidable (FourLength length) := by
  unfold FourLength
  infer_instance

/-- A directly decidable square predicate on four explicit vertices.  This is
the practical finite interface for concrete transfer fixtures: it quantifies
over `V⁴`, not over walks or graphs. -/
def NoSquare {V : Type u} (G : SimpleGraph V) : Prop :=
  ∀ a b c d : V,
    a ≠ b → a ≠ c → a ≠ d → b ≠ c → b ≠ d → c ≠ d →
    G.Adj a b → G.Adj b c → G.Adj c d → G.Adj d a → False

/-- An explicit four-vertex square exclusion is exactly enough to rule out
the length-four target used by this profile. -/
theorem fourFree_of_noSquare {V : Type u} {G : SimpleGraph V}
    (noSquare : NoSquare G) : ¬HasCycleWithLength G FourLength := by
  rintro ⟨cycle⟩
  have lengthEq : cycle.walk.length = 4 := cycle.length_ok
  let a := cycle.walk.getVert 0
  let b := cycle.walk.getVert 1
  let c := cycle.walk.getVert 2
  let d := cycle.walk.getVert 3
  have distinct {i j : Nat} (iLe : i ≤ 3) (jLe : j ≤ 3)
      (indicesNe : i ≠ j) :
      cycle.walk.getVert i ≠ cycle.walk.getVert j := by
    intro verticesEq
    apply indicesNe
    apply cycle.isCycle.getVert_injOn'
    · simp only [Set.mem_setOf_eq, lengthEq]
      omega
    · simp only [Set.mem_setOf_eq, lengthEq]
      omega
    · exact verticesEq
  apply noSquare a b c d
  · exact distinct (by omega) (by omega) (by omega)
  · exact distinct (by omega) (by omega) (by omega)
  · exact distinct (by omega) (by omega) (by omega)
  · exact distinct (by omega) (by omega) (by omega)
  · exact distinct (by omega) (by omega) (by omega)
  · exact distinct (by omega) (by omega) (by omega)
  · exact cycle.walk.adj_getVert_succ (i := 0) (by omega)
  · exact cycle.walk.adj_getVert_succ (i := 1) (by omega)
  · exact cycle.walk.adj_getVert_succ (i := 2) (by omega)
  · have edge := cycle.walk.adj_getVert_succ (i := 3) (by omega)
    have endpoint : cycle.walk.getVert 4 = cycle.vertex := by
      rw [← lengthEq, SimpleGraph.Walk.getVert_length]
    rw [endpoint] at edge
    simpa [a, d] using edge

/-- Literal four-edge closed walk around a square. -/
def squareWalk {V : Type u} {G : SimpleGraph V}
    {a b c d : V} (ab : G.Adj a b) (bc : G.Adj b c)
    (cd : G.Adj c d) (da : G.Adj d a) : G.Walk a a :=
  .cons ab (.cons bc (.cons cd (.cons da .nil)))

theorem squareWalk_length {V : Type u} {G : SimpleGraph V}
    {a b c d : V} (ab : G.Adj a b) (bc : G.Adj b c)
    (cd : G.Adj c d) (da : G.Adj d a) :
    (squareWalk ab bc cd da).length = 4 := rfl

theorem squareWalk_isCycle {V : Type u} {G : SimpleGraph V}
    {a b c d : V} (ab : G.Adj a b) (bc : G.Adj b c)
    (cd : G.Adj c d) (da : G.Adj d a)
    (a_ne_c : a ≠ c) (b_ne_d : b ≠ d) :
    (squareWalk ab bc cd da).IsCycle := by
  rw [SimpleGraph.Walk.isCycle_def, SimpleGraph.Walk.isTrail_def]
  simp [squareWalk, a_ne_c, Ne.symm a_ne_c, b_ne_d, ab.ne, ab.symm.ne,
    bc.ne, cd.ne, da.ne, da.symm.ne]

/-- Four-cycle certificate generated by a literal square. -/
def squareCycle {V : Type u} {G : SimpleGraph V}
    {a b c d : V} (ab : G.Adj a b) (bc : G.Adj b c)
    (cd : G.Adj c d) (da : G.Adj d a)
    (a_ne_c : a ≠ c) (b_ne_d : b ≠ d) :
    CycleWithLength G FourLength where
  vertex := a
  walk := squareWalk ab bc cd da
  isCycle := squareWalk_isCycle ab bc cd da a_ne_c b_ne_d
  length_ok := rfl

/-! ## CT1 exact-four-cycle avoidance profile -/

/-- Certificate encoding that validates one literal length-four cycle and
never searches a walk universe. -/
def encoding (V : Type u) :=
  cycleTargetCertificateEncoding
    (P := FiniteObject.problem V) (fun object => object) FourLength

def input {V : Type u} (object : FiniteObject V) :
    CT1.Input (FiniteObject.problem V) where
  context := object.context

def runAvoiding {V : Type u} (object : FiniteObject V)
    (fourFree : ¬HasCycleWithLength object.graph FourLength) :=
  (encoding V).runAvoiding (input object) fourFree

theorem runAvoiding_terminal {V : Type u} (object : FiniteObject V)
    (fourFree : ¬HasCycleWithLength object.graph FourLength) :
    (runAvoiding object fourFree).result.terminal = .avoiding :=
  (runAvoiding object fourFree).terminal_eq

theorem runAvoiding_trace {V : Type u} (object : FiniteObject V)
    (fourFree : ¬HasCycleWithLength object.graph FourLength) :
    (runAvoiding object fourFree).result.trace =
      [.entry, .equivalenceCertification, .realizationDecision,
        .avoidingTerminal] :=
  (runAvoiding object fourFree).trace_eq

theorem runAvoiding_checks {V : Type u} (object : FiniteObject V)
    (fourFree : ¬HasCycleWithLength object.graph FourLength) :
    (runAvoiding object fourFree).checks = 0 :=
  (runAvoiding object fourFree).checks_eq

theorem runAvoiding_total {V : Type u} (object : FiniteObject V)
    (fourFree : ¬HasCycleWithLength object.graph FourLength) :
    ∃ run : CT1.CertifiedAvoidingRun (encoding V).spec (input object),
      run.result.terminal = .avoiding ∧
      run.result.trace =
        [.entry, .equivalenceCertification, .realizationDecision,
          .avoidingTerminal] :=
  ⟨runAvoiding object fourFree, runAvoiding_terminal object fourFree,
    runAvoiding_trace object fourFree⟩

theorem runAvoiding_polynomial {V : Type u} (object : FiniteObject V)
    (fourFree : ¬HasCycleWithLength object.graph FourLength) :
    (runAvoiding object fourFree).checks ≤ 1 := by
  rw [runAvoiding_checks object fourFree]
  decide

/-- Avoidance of any cycle predicate accepting four excludes literal
four-cycles. -/
theorem fourFree_of_targetAvoiding
    {V : Type u}
    (base : MinimumDegreeCycle.StaticInput V (fun _object => Unit))
    (object : FiniteObject V) (acceptsFour : base.LengthOK 4)
    (avoids : ¬base.Target object) :
    ¬HasCycleWithLength object.graph FourLength := by
  rintro ⟨cycle⟩
  apply avoids
  exact ⟨{
    vertex := cycle.vertex
    walk := cycle.walk
    isCycle := cycle.isCycle
    length_ok := by
      rw [cycle.length_ok]
      exact acceptsFour
  }⟩

/-- A four-cycle-free graph has matching neighbourhoods: two consecutive
edges inside one neighbourhood must be the same undirected edge. -/
theorem neighborhood_isMatching
    {V : Type u} {G : SimpleGraph V}
    (fourFree : ¬HasCycleWithLength G FourLength)
    {center left middle right : V}
    (centerLeft : G.Adj center left)
    (centerMiddle : G.Adj center middle)
    (centerRight : G.Adj center right)
    (leftMiddle : G.Adj left middle)
    (middleRight : G.Adj middle right) :
    left = right := by
  by_contra leftNeRight
  apply fourFree
  exact ⟨squareCycle centerLeft leftMiddle middleRight centerRight.symm
    centerMiddle.ne leftNeRight⟩

/-- Two distinct nonadjacent neighbours of one centre have no common
neighbour away from the centre in a four-cycle-free graph. -/
theorem nonadjacentNeighbors_noCommonOutside
    {V : Type u} {G : SimpleGraph V}
    (fourFree : ¬HasCycleWithLength G FourLength)
    {center left right common : V}
    (leftNeRight : left ≠ right)
    (commonNeCenter : common ≠ center)
    (centerLeft : G.Adj center left)
    (centerRight : G.Adj center right)
    (leftCommon : G.Adj left common)
    (rightCommon : G.Adj right common) : False := by
  apply fourFree
  exact ⟨squareCycle centerLeft leftCommon rightCommon.symm centerRight.symm
    (Ne.symm commonNeCenter) leftNeRight⟩

/-- Complete reusable output for the exact-four CT1 audit and its two local
neighbourhood consequences. -/
structure VerifiedStage {V : Type u} (object : FiniteObject V) : Prop where
  fourFree : ¬HasCycleWithLength object.graph FourLength
  terminal : (runAvoiding object fourFree).result.terminal = .avoiding
  trace : (runAvoiding object fourFree).result.trace =
    [.entry, .equivalenceCertification, .realizationDecision,
      .avoidingTerminal]
  checks : (runAvoiding object fourFree).checks = 0
  total : ∃ run : CT1.CertifiedAvoidingRun (encoding V).spec (input object),
    run.result.terminal = .avoiding ∧
      run.result.trace =
        [.entry, .equivalenceCertification, .realizationDecision,
          .avoidingTerminal]
  polynomial : (runAvoiding object fourFree).checks ≤ 1
  neighborhoodMatching : ∀ {center left middle right : V},
    object.graph.Adj center left →
    object.graph.Adj center middle →
    object.graph.Adj center right →
    object.graph.Adj left middle →
    object.graph.Adj middle right → left = right
  noCommonOutside : ∀ {center left right common : V},
    left ≠ right → common ≠ center →
    object.graph.Adj center left → object.graph.Adj center right →
    object.graph.Adj left common → object.graph.Adj right common → False

def verifiedStage {V : Type u} (object : FiniteObject V)
    (fourFree : ¬HasCycleWithLength object.graph FourLength) :
    VerifiedStage object where
  fourFree := fourFree
  terminal := runAvoiding_terminal object fourFree
  trace := runAvoiding_trace object fourFree
  checks := runAvoiding_checks object fourFree
  total := runAvoiding_total object fourFree
  polynomial := runAvoiding_polynomial object fourFree
  neighborhoodMatching := neighborhood_isMatching fourFree
  noCommonOutside := nonadjacentNeighbors_noCommonOutside fourFree

end StructuralExhaustion.Graph.HighCenterStructure
