import StructuralExhaustion.CT2.LocalDeletion
import StructuralExhaustion.Graph.CycleCertificate

namespace StructuralExhaustion.Graph

open StructuralExhaustion

universe uVertex uBranch

/-!
# Minimum-degree cycle CT profile

This module is the reusable boundary between Mathlib finite graphs and the
domain-independent CT machines.  An application supplies exactly three
pieces of static data: its branch-state family, a minimum-degree threshold,
and a predicate on cycle lengths.  The framework then generates the shared
problem and target together with certificate-driven CT1 and local-deletion
CT2 surfaces.
-/

namespace MinimumDegreeCycle

/-- Complete problem-specific input for the common minimum-degree/cycle
profile.  No CT node result or proof of a machine transition is an author
field. -/
structure StaticInput
    (V : Type uVertex)
    (BranchState : FiniteObject V → Type uBranch) where
  minimumDegree : Nat
  LengthOK : Nat → Prop

namespace StaticInput

variable {V : Type uVertex}
variable {BranchState : FiniteObject V → Type uBranch}

/-- Domain-independent problem generated from the graph profile. -/
def problem (input : StaticInput V BranchState) :
    Core.Problem.{uVertex, uBranch} where
  Ambient := FiniteObject V
  Baseline := fun object => input.minimumDegree ≤ object.minDegree
  rank := FiniteObject.edgeCount
  BranchState := BranchState

/-- The public mathematical target generated by the profile. -/
def Target (input : StaticInput V BranchState)
    (object : FiniteObject V) : Prop :=
  HasCycleWithLength object.graph input.LengthOK

/-- Certificate-driven CT1 surface for concrete Mathlib cycles. -/
def targetEncoding (input : StaticInput V BranchState) :
    CT1.TargetCertificateEncoding (P := input.problem) input.Target :=
  cycleTargetCertificateEncoding (P := input.problem) (fun object => object)
    input.LengthOK

abbrev ct1Spec (input : StaticInput V BranchState) :=
  input.targetEncoding.spec

abbrev ct1TargetBridge (input : StaticInput V BranchState) :=
  input.targetEncoding.bridge

/-- Baseline decision procedure generated from Mathlib's natural-number
order and minimum-degree computation. -/
def baselineDecidable (input : StaticInput V BranchState)
    (object : FiniteObject V) :
    Decidable (input.problem.Baseline object) := by
  change Decidable (input.minimumDegree ≤ object.minDegree)
  infer_instance

/-- Darts with one unit of endpoint degree slack are exactly the deletable
CT2 pieces.  Every dart is admissible; a local CT2 run validates the explicitly
supplied dart. -/
def ct2Pieces (input : StaticInput V BranchState) :
    CT2.PieceSystem input.problem where
  Piece := fun object => object.graph.Dart
  pieces := fun object => object.input.darts
  Proper := fun {object} dart =>
    input.minimumDegree + 1 ≤ object.degree dart.fst ∧
      input.minimumDegree + 1 ≤ object.degree dart.snd
  Admissible := fun _state _dart => True
  properDecidable := fun _dart => by infer_instance
  admissibleDecidable := fun _state _dart => .isTrue trivial

/-- Proof-carrying Mathlib dart deletion with edge count as rank. -/
def ct2Reductions (input : StaticInput V BranchState) :
    CT2.ReductionOps input.ct2Pieces where
  delete := fun {object} dart => {
    value := object.deleteDart dart
    decreases := object.edgeCount_deleteDart_lt dart
  }

/-- Local deletion capability.  It contains no target decision procedure. -/
def ct2Capability (input : StaticInput V BranchState) :
    CT2.LocalDeletionCapability input.problem where
  pieces := input.ct2Pieces
  reductions := input.ct2Reductions

/-- Both CT2 semantic obligations follow from the Mathlib graph support
layer: endpoint slack preserves minimum degree, and graph inclusion transports
any accepted cycle back to the source. -/
def ct2DeletionRule (input : StaticInput V BranchState) :
    CT2.LocalDeletionClosureRule (Target := input.Target)
      input.ct2Capability where
  preservesBaseline := by
    intro object _state dart proper _admissible baseline
    exact object.deleteDart_preserves_minDegree dart input.minimumDegree
      baseline proper.1 proper.2
  targetMonotone := by
    intro object _state dart _proper _admissible _baseline
    exact object.hasCycleWithLength_of_deleteDart dart

/-- Generic deletion criticality: in a minimal counterexample every edge has
an endpoint whose degree is exactly the baseline threshold. -/
theorem dart_has_tight_endpoint (input : StaticInput V BranchState)
    (ctx : Core.MinimalCounterexampleContext input.problem input.Target)
    (dart : ctx.G.graph.Dart) :
    ctx.G.degree dart.fst = input.minimumDegree ∨
      ctx.G.degree dart.snd = input.minimumDegree := by
  have notSlack : ¬(input.minimumDegree + 1 ≤ ctx.G.degree dart.fst ∧
      input.minimumDegree + 1 ≤ ctx.G.degree dart.snd) :=
    input.ct2DeletionRule.notProper ctx dart trivial
  have fstLower : input.minimumDegree ≤ ctx.G.degree dart.fst :=
    ctx.baseline.trans (ctx.G.minDegree_le_degree dart.fst)
  have sndLower : input.minimumDegree ≤ ctx.G.degree dart.snd :=
    ctx.baseline.trans (ctx.G.minDegree_le_degree dart.snd)
  omega

/-- Exact deletion-C2 execution for an explicitly supplied slack dart. -/
def heavyDartRun (input : StaticInput V BranchState)
    (ctx : Core.MinimalCounterexampleContext input.problem input.Target)
    (dart : ctx.G.graph.Dart)
    (slack : input.minimumDegree + 1 ≤ ctx.G.degree dart.fst ∧
      input.minimumDegree + 1 ≤ ctx.G.degree dart.snd) :
    CT2.LocalDeletionRun input.ct2Capability ctx
      ⟨⟨dart, slack, trivial⟩⟩ :=
  input.ct2DeletionRule.run ctx ⟨⟨dart, slack, trivial⟩⟩

end StaticInput

end MinimumDegreeCycle

end StructuralExhaustion.Graph
