import Erdos64EG.CT9HomogeneousPattern
import Erdos64EG.SurplusScaleSplit

#print axioms StructuralExhaustion.Core.GreedyMatchingStar.exists_pattern_of_cap_lt_card
#print axioms StructuralExhaustion.Graph.SurplusHomogeneousPattern.audit
#print axioms Erdos64EG.Internal.exists_verifiedHomogeneousPatternPrefix
#print axioms Erdos64EG.Internal.exists_verifiedSurplusScaleRoutingPrefix
