import Erdos64EG.Future.P13WeightedColdRestrictedF5Representatives

namespace Erdos64EG.Internal.P13WeightedColdRestrictedPrefixPackage.Tests

#check P13WeightedColdRestrictedPrefixPackage.repeatedRepresentatives
#check P13WeightedColdRestrictedPrefixPackage.repeatedRepresentatives_source
#check P13WeightedColdRestrictedPrefixPackage.repeatedRepresentatives_replacement
#check P13WeightedColdRestrictedPrefixPackage.repeatedRepresentatives_increment_exact
#check P13WeightedColdRestrictedPrefixPackage.repeatedRepresentatives_targetUniversal
#check P13WeightedColdRestrictedPrefixPackage.repeatedResponseTable

#print axioms P13WeightedColdRestrictedPrefixPackage.repeatedRepresentatives_increment_exact
#print axioms P13WeightedColdRestrictedPrefixPackage.repeatedRepresentatives_targetUniversal
#print axioms P13WeightedColdRestrictedPrefixPackage.repeatedResponseTable

end Erdos64EG.Internal.P13WeightedColdRestrictedPrefixPackage.Tests
