import Erdos64EG.Future.P13WeightedColdRestrictedComponentSchedule

namespace Erdos64EG.Internal

#check p13WeightedColdBranchExcessSchedule_nodup
#check p13WeightedColdRestrictedEntries_sources
#check p13WeightedColdRestrictedEntries_sources_nodup
#check p13WeightedColdRestrictedComponentSchedule_sources
#check p13WeightedColdRestrictedComponentSchedule_sources_nodup

#print axioms p13WeightedColdRestrictedComponentSchedule_sources
#print axioms p13WeightedColdRestrictedComponentSchedule_sources_nodup

end Erdos64EG.Internal
