import Erdos64EG.Future.P13WeightedColdRestrictedColdGermFrontier

namespace Erdos64EG.Internal

#check P13WeightedColdRestrictedPrefixPackage.ambientVertex_injective
#check P13WeightedColdRestrictedPrefixPackage.currentAmbientEndpoint_ne_of_val_lt
#check P13WeightedColdRestrictedPrefixPackage.repeated_actual_endpoint_ne
#check P13WeightedColdRestrictedPrefixPackage.repeated_stage_span_le_QCold
#check P13WeightedColdRestrictedPrefixPackage.repeatedSpanInput
#check P13WeightedColdRestrictedPrefixPackage.repeatedSpanInput_card_le_QCold_add_one
#check P13WeightedColdRestrictedPrefixPackage.repeatedSpanEscapingIncidences
#check P13WeightedColdRestrictedPrefixPackage.repeatedSpanEscapingIncidences_eq_nil_iff
#check P13WeightedColdRestrictedPrefixPackage.repeatedSpanOwnershipDecidable
#check P13WeightedColdRestrictedPrefixPackage.RepeatedColdGermFrontier
#check P13WeightedColdRestrictedPrefixPackage.repeatedColdGermFrontier
#check P13WeightedColdRestrictedPrefixPackage.TerminalColdGermFrontier
#check P13WeightedColdRestrictedPrefixPackage.terminalColdGermFrontier

#print axioms P13WeightedColdRestrictedPrefixPackage.repeated_actual_endpoint_ne
#print axioms P13WeightedColdRestrictedPrefixPackage.repeatedSpanInput_card_le_QCold_add_one
#print axioms P13WeightedColdRestrictedPrefixPackage.repeatedColdGermFrontier
#print axioms P13WeightedColdRestrictedPrefixPackage.terminalColdGermFrontier

end Erdos64EG.Internal
