import Erdos64EG.Future.TypeANode93VisibleFamily

namespace Erdos64EG.Tests.TypeANode93VisibleFamily

open Erdos64EG.Internal

#check TypeANode93VisibleFamily.VerifiedNode93Residual.node95Input
#check TypeANode93VisibleFamily.VerifiedNode93Residual.node95Family
#check TypeANode93VisibleFamily.VerifiedNode93Residual.node95Family_has_four
#check TypeANode93VisibleFamily.VerifiedNode93Residual.node95_loads_distinct
#check TypeANode93VisibleFamily.VerifiedNode93Residual.classifyContinuations
#print axioms TypeANode93VisibleFamily.VerifiedNode93Residual.node95Family_has_four
#print axioms TypeANode93VisibleFamily.VerifiedNode93Residual.node95_loads_distinct

end Erdos64EG.Tests.TypeANode93VisibleFamily
