import Hypostructure.CT11.Theorems

/-!
# CT11 ordered negative-budget profile

This profile is the minimum author surface for an everywhere-admissible
ordered additive decomposition whose exact total is already registered as
strictly negative in the predecessor ledger.
-/

namespace Hypostructure.CT11

universe uPrevious uCell

/-- Reusable ordered additive profile with a registered negative total. -/
structure OrderedNegativeBudgetProfile (Previous : Type uPrevious) where
  Cell : Previous -> Type uCell
  localBudget : (previous : Previous) -> Cell previous -> Int
  cells : Core.Residual.Query Previous fun previous =>
    Core.Finite.Enumeration (Cell previous)
  negativeTotal : Core.Residual.Query Previous fun previous =>
    ((cells.read previous).values.map (localBudget previous)).sum < 0
  inputSize : Previous -> Nat
  workCoefficient : Nat
  workDegree : Nat
  workBound : forall previous,
    localCheckBound (cells.read previous) <=
      workCoefficient * (inputSize previous + 1) ^ workDegree

namespace OrderedNegativeBudgetProfile

/-- Shared CT11 semantics generated by an everywhere-admissible profile. -/
def spec (profile : OrderedNegativeBudgetProfile.{uPrevious, uCell} Previous) :
    Spec Previous where
  Cell := profile.Cell
  Admissible := fun _previous _cell => True
  localBudget := profile.localBudget

/-- Executable CT11 capability generated by the ordered profile. -/
def capability
    (profile : OrderedNegativeBudgetProfile.{uPrevious, uCell} Previous) :
    Capability profile.spec where
  cells := profile.cells
  admissibleDecidable := fun _previous _cell => by
    change Decidable True
    infer_instance
  negativeTotal := profile.negativeTotal
  inputSize := profile.inputSize
  workCoefficient := profile.workCoefficient
  workDegree := profile.workDegree
  workBound := profile.workBound

/-- Exact CT11 execution generated from the profile. -/
def run (profile : OrderedNegativeBudgetProfile.{uPrevious, uCell} Previous)
    (previous : Previous) :
    ExecutionResult profile.spec profile.capability :=
  CT11.run profile.spec profile.capability previous

/-- An everywhere-admissible profile always reaches localization. -/
theorem run_terminal_localized
    (profile : OrderedNegativeBudgetProfile.{uPrevious, uCell} Previous)
    (previous : Previous) :
    (profile.run previous).terminal = .localizedDeficit := by
  apply Outcome.terminal_localizedDeficit_of_all_admissible
    (outcome := (profile.run previous).outcome)
  intro _cell _member
  trivial

/-- Canonical first negative cell selected by the generated profile run. -/
def residual
    (profile : OrderedNegativeBudgetProfile.{uPrevious, uCell} Previous)
    (previous : Previous) :
    LocalizedDeficitResidual profile.capability previous :=
  (profile.run previous).localizedResidual
    (profile.run_terminal_localized previous)

/-- The profile's selected cell has strict negative local budget. -/
theorem residual_negative
    (profile : OrderedNegativeBudgetProfile.{uPrevious, uCell} Previous)
    (previous : Previous) :
    profile.localBudget previous (profile.residual previous).cell < 0 :=
  (profile.residual previous).negative

end OrderedNegativeBudgetProfile

end Hypostructure.CT11
