import StructuralExhaustion.CT11.Theorems

namespace StructuralExhaustion.CT11

universe uAmbient uBranch uCell

/-- Minimal specialization of CT11 for an everywhere-admissible finite
collection whose total integer budget is negative. -/
structure NegativeBudgetProfile
    (P : Core.Problem.{uAmbient, uBranch}) where
  Cell : Type uCell
  localBudget : Core.BranchContext P → Cell → Int

namespace NegativeBudgetProfile

/-- The general CT11 capability generated by an everywhere-admissible
negative-budget profile. -/
def capability (profile : NegativeBudgetProfile P) : Capability P where
  Cell := profile.Cell
  Admissible := fun _ _ => True
  admissibleDecidable := fun _ _ => inferInstance
  localBudget := profile.localBudget

/-- Construct the exact CT11 input from invocation-local cells and the global
negative-sum proof. -/
def input (profile : NegativeBudgetProfile P)
    (context : Core.BranchContext P)
    (cells : Core.OrderedCollection profile.Cell)
    (deficit : (cells.values.map (profile.localBudget context)).sum < 0) :
    Input profile.capability where
  context := context
  cells := cells
  deficit := deficit

/-- Exact CT11 execution for the negative-budget profile. -/
def run (profile : NegativeBudgetProfile P)
    (context : Core.BranchContext P)
    (cells : Core.OrderedCollection profile.Cell)
    (deficit : (cells.values.map (profile.localBudget context)).sum < 0) :=
  CT11.run profile.capability (profile.input context cells deficit)

/-- An everywhere-admissible profile cannot reach CT11's admissibility-gap
terminal. -/
theorem run_terminal_localized (profile : NegativeBudgetProfile P)
    (context : Core.BranchContext P)
    (cells : Core.OrderedCollection profile.Cell)
    (deficit : (cells.values.map (profile.localBudget context)).sum < 0) :
    (profile.run context cells deficit).terminal = .localized := by
  generalize runEqual : profile.run context cells deficit = result
  cases result with
  | mk terminal path outcome =>
      cases outcome with
      | gap residual => exact (residual.inadmissible trivial).elim
      | localized _ => rfl

namespace ExecutionResult

/-- Recover terminal-indexed localized evidence from an exact CT11 result. -/
def localizedResidual
    {profile : NegativeBudgetProfile P}
    {context : Core.BranchContext P}
    {cells : Core.OrderedCollection profile.Cell}
    {deficit : (cells.values.map (profile.localBudget context)).sum < 0}
    (result : CT11.ExecutionResult profile.capability
      (profile.input context cells deficit))
    (terminal : result.terminal = .localized) :
    LocalizedDeficitResidual profile.capability
      (profile.input context cells deficit) := by
  cases result with
  | mk foundTerminal path outcome =>
      cases outcome with
      | gap _ => cases terminal
      | localized residual => exact residual

end ExecutionResult

/-- Canonical first negative-budget cell selected by the CT11 reference run. -/
def residual (profile : NegativeBudgetProfile P)
    (context : Core.BranchContext P)
    (cells : Core.OrderedCollection profile.Cell)
    (deficit : (cells.values.map (profile.localBudget context)).sum < 0) :
    LocalizedDeficitResidual profile.capability
      (profile.input context cells deficit) :=
  ExecutionResult.localizedResidual (profile.run context cells deficit)
    (profile.run_terminal_localized context cells deficit)

end NegativeBudgetProfile

end StructuralExhaustion.CT11
