import Hypostructure.CT4.Search

/-!
# CT4 accumulated execution

The private routed value is selected only by Core finite-search and binary
decision stages.  A completed CT4 execution contributes exactly one extension
to its literal predecessor ledger.
-/

namespace Hypostructure.CT4

universe uPrevious uDemand uPayer

variable {Previous : Type uPrevious}
  {spec : Spec.{uPrevious, uDemand, uPayer} Previous}

/-- The four exhaustive CT4 terminals. -/
inductive Terminal where
  | missingPayer
  | overloadedFibre
  | c4
  | capacity
  deriving DecidableEq, Repr

/-- Audit nodes in the complete deterministic charging flow. -/
inductive NodeId where
  | entry
  | assignment
  | availabilitySearch
  | fibreComputation
  | overloadSearch
  | capacityComparison
  | missingPayerTerminal
  | overloadedFibreTerminal
  | c4Terminal
  | capacityTerminal
  deriving DecidableEq, Repr

/-- Terminal-indexed evidence generated by the CT4 machine. -/
inductive Outcome (capability : Capability spec) (previous : Previous) :
    Terminal -> Type _ where
  | missingPayer (assignment : AssignmentState capability previous)
      (residual : MissingPayerResidual capability previous assignment) :
      Outcome capability previous .missingPayer
  | overloadedFibre (total : TotalAssignmentState capability previous)
      (residual : OverloadedFibreResidual capability previous total) :
      Outcome capability previous .overloadedFibre
  | c4 (total : TotalAssignmentState capability previous)
      (bounded : BoundedFibreState capability previous total)
      (certificate : C4Certificate capability previous) :
      Outcome capability previous .c4
  | capacity (total : TotalAssignmentState capability previous)
      (bounded : BoundedFibreState capability previous total)
      (residual : CapacityResidual capability previous) :
      Outcome capability previous .capacity

/-- Terminal-indexed exact CT4 trace. -/
inductive Trace : Terminal -> Type where
  | missingPayer : Trace .missingPayer
  | overloadedFibre : Trace .overloadedFibre
  | c4 : Trace .c4
  | capacity : Trace .capacity

namespace Trace

/-- Observable node sequence of a typed trace. -/
def nodes : {terminal : Terminal} -> Trace terminal -> List NodeId
  | .missingPayer, .missingPayer =>
      [.entry, .assignment, .availabilitySearch, .missingPayerTerminal]
  | .overloadedFibre, .overloadedFibre =>
      [.entry, .assignment, .availabilitySearch, .fibreComputation,
        .overloadSearch, .overloadedFibreTerminal]
  | .c4, .c4 =>
      [.entry, .assignment, .availabilitySearch, .fibreComputation,
        .overloadSearch, .capacityComparison, .c4Terminal]
  | .capacity, .capacity =>
      [.entry, .assignment, .availabilitySearch, .fibreComputation,
        .overloadSearch, .capacityComparison, .capacityTerminal]

/-- Canonical node sequence fixed by each semantic terminal. -/
def expectedNodes : Terminal -> List NodeId
  | .missingPayer =>
      [.entry, .assignment, .availabilitySearch, .missingPayerTerminal]
  | .overloadedFibre =>
      [.entry, .assignment, .availabilitySearch, .fibreComputation,
        .overloadSearch, .overloadedFibreTerminal]
  | .c4 =>
      [.entry, .assignment, .availabilitySearch, .fibreComputation,
        .overloadSearch, .capacityComparison, .c4Terminal]
  | .capacity =>
      [.entry, .assignment, .availabilitySearch, .fibreComputation,
        .overloadSearch, .capacityComparison, .capacityTerminal]

theorem nodes_eq_expected : {terminal : Terminal} ->
    (trace : Trace terminal) -> trace.nodes = expectedNodes terminal
  | .missingPayer, .missingPayer => rfl
  | .overloadedFibre, .overloadedFibre => rfl
  | .c4, .c4 => rfl
  | .capacity, .capacity => rfl

end Trace

/-- Private framework-routed CT4 value. -/
structure Routed (capability : Capability spec) (previous : Previous) where
  private mk ::
  terminal : Terminal
  outcome : Outcome capability previous terminal

/-- Execute the complete Core-owned routing tree. -/
def routeReference (capability : Capability spec) (previous : Previous) :
    Routed capability previous :=
  let assignment := computeAssignment capability previous
  let availability := routeAvailability capability previous assignment
  match availability.added with
  | .yesBranch hasMissing =>
      .mk .missingPayer (.missingPayer assignment
        (availability.previous.hitOfHasHit hasMissing))
  | .noBranch noMissing =>
      let total := totalAssignmentOfAvoids assignment noMissing
      let overload := routeOverload capability previous total
      match overload.added with
      | .yesBranch hasOverload =>
          .mk .overloadedFibre (.overloadedFibre total
            (overload.previous.hitOfHasHit hasOverload))
      | .noBranch bounded =>
          let comparison := compareCapacity capability previous
          match comparison.added with
          | .yesBranch certificate =>
              .mk .c4 (.c4 total bounded certificate)
          | .noBranch residual =>
              .mk .capacity (.capacity total bounded residual)

/-- Unique exact trace derived from terminal-indexed evidence. -/
def traceOfOutcome {capability : Capability spec} {previous : Previous}
    {terminal : Terminal} (outcome : Outcome capability previous terminal) :
    Trace terminal := by
  cases outcome with
  | missingPayer _ _ => exact .missingPayer
  | overloadedFibre _ _ => exact .overloadedFibre
  | c4 _ _ _ => exact .c4
  | capacity _ _ _ => exact .capacity

/-- Unique trace selected by a private routed result. -/
def traceOfRouted {capability : Capability spec} {previous : Previous}
    (routed : Routed capability previous) : Trace routed.terminal :=
  traceOfOutcome routed.outcome

/-- Exact primitive checks charged by each branch.

Assignment checks are exact first-hit counts.  Availability and overload
searches pay their exact prefixes.  Each inspected payer additionally scans
the complete demand schedule to compute its fibre weight. -/
def outcomeChecks {capability : Capability spec} {previous : Previous} :
    {terminal : Terminal} -> Outcome capability previous terminal -> Nat
  | .missingPayer, .missingPayer assignment residual =>
      assignment.checks + residual.index.1 + 1
  | .overloadedFibre, .overloadedFibre total residual =>
      total.assignment.checks + (capability.demandsAt previous).card +
        (residual.index.1 + 1) *
          ((capability.demandsAt previous).card + 1)
  | .c4, .c4 total _bounded _certificate =>
      total.assignment.checks + (capability.demandsAt previous).card +
        (capability.payersAt previous).card *
          ((capability.demandsAt previous).card + 1) + 1
  | .capacity, .capacity total _bounded _residual =>
      total.assignment.checks + (capability.demandsAt previous).card +
        (capability.payersAt previous).card *
          ((capability.demandsAt previous).card + 1) + 1

/-- Branch-exact work never exceeds the complete prescribed CT4 schedule. -/
theorem outcomeChecks_le_limit {capability : Capability spec}
    {previous : Previous} {terminal : Terminal}
    (outcome : Outcome capability previous terminal) :
    outcomeChecks outcome <= localCheckBound
      (capability.demandsAt previous) (capability.payersAt previous) := by
  cases outcome with
  | missingPayer assignment residual =>
      have assignmentBound := assignment.checks_le_product
      have availabilityBound : residual.index.1 + 1 <=
          (capability.demandsAt previous).card :=
        Nat.succ_le_iff.mpr residual.index.isLt
      calc
        assignment.checks + residual.index.1 + 1 =
            assignment.checks + (residual.index.1 + 1) := by omega
        _ <= (capability.demandsAt previous).card *
              (capability.payersAt previous).card +
            (capability.demandsAt previous).card :=
          Nat.add_le_add assignmentBound availabilityBound
        _ <= ((capability.demandsAt previous).card *
              (capability.payersAt previous).card +
            (capability.demandsAt previous).card) +
            ((capability.demandsAt previous).card *
              (capability.payersAt previous).card +
            (capability.payersAt previous).card + 1) :=
          Nat.le_add_right _ _
        _ = localCheckBound (capability.demandsAt previous)
              (capability.payersAt previous) := by
          simp only [localCheckBound]
          ring
  | overloadedFibre total residual =>
      have assignmentBound := total.assignment.checks_le_product
      have overloadPrefix : residual.index.1 + 1 <=
          (capability.payersAt previous).card :=
        Nat.succ_le_iff.mpr residual.index.isLt
      have overloadBound :
          (residual.index.1 + 1) *
              ((capability.demandsAt previous).card + 1) <=
            (capability.payersAt previous).card *
              ((capability.demandsAt previous).card + 1) :=
        Nat.mul_le_mul_right _ overloadPrefix
      calc
        total.assignment.checks +
              (capability.demandsAt previous).card +
            (residual.index.1 + 1) *
              ((capability.demandsAt previous).card + 1) <=
            (capability.demandsAt previous).card *
                (capability.payersAt previous).card +
              (capability.demandsAt previous).card +
            (capability.payersAt previous).card *
              ((capability.demandsAt previous).card + 1) :=
          Nat.add_le_add (Nat.add_le_add_right assignmentBound _) overloadBound
        _ <= (capability.demandsAt previous).card *
                (capability.payersAt previous).card +
              (capability.demandsAt previous).card +
            (capability.payersAt previous).card *
                ((capability.demandsAt previous).card + 1) + 1 :=
          Nat.le_succ _
        _ = localCheckBound (capability.demandsAt previous)
              (capability.payersAt previous) := by
          simp only [localCheckBound]
          ring
  | c4 total _bounded _certificate =>
      calc
        total.assignment.checks +
              (capability.demandsAt previous).card +
            (capability.payersAt previous).card *
                ((capability.demandsAt previous).card + 1) + 1 <=
            (capability.demandsAt previous).card *
                (capability.payersAt previous).card +
              (capability.demandsAt previous).card +
            (capability.payersAt previous).card *
                ((capability.demandsAt previous).card + 1) + 1 :=
          by
            simpa [Nat.add_assoc] using Nat.add_le_add_right
              total.assignment.checks_le_product
              ((capability.demandsAt previous).card +
                (capability.payersAt previous).card *
                  ((capability.demandsAt previous).card + 1) + 1)
        _ = localCheckBound (capability.demandsAt previous)
              (capability.payersAt previous) := by
          simp only [localCheckBound]
          ring
  | capacity total _bounded _residual =>
      calc
        total.assignment.checks +
              (capability.demandsAt previous).card +
            (capability.payersAt previous).card *
                ((capability.demandsAt previous).card + 1) + 1 <=
            (capability.demandsAt previous).card *
                (capability.payersAt previous).card +
              (capability.demandsAt previous).card +
            (capability.payersAt previous).card *
                ((capability.demandsAt previous).card + 1) + 1 :=
          by
            simpa [Nat.add_assoc] using Nat.add_le_add_right
              total.assignment.checks_le_product
              ((capability.demandsAt previous).card +
                (capability.payersAt previous).card *
                  ((capability.demandsAt previous).card + 1) + 1)
        _ = localCheckBound (capability.demandsAt previous)
              (capability.payersAt previous) := by
          simp only [localCheckBound]
          ring

/-- One accumulated CT4 stage: the literal predecessor plus one private
routed output. -/
abbrev Stage (spec : Spec.{uPrevious, uDemand, uPayer} Previous)
    (capability : Capability spec) :=
  Core.Residual.Ledger.Extension Previous fun previous =>
    Routed capability previous

/-- Closed public CT4 result. -/
structure ExecutionResult (spec : Spec.{uPrevious, uDemand, uPayer} Previous)
    (capability : Capability spec) where
  private mk ::
  stage : Stage spec capability
  trace : Trace stage.added.terminal
  checks : Nat
  checks_eq : checks = outcomeChecks stage.added.outcome

namespace ExecutionResult

/-- Terminal derived from retained routed evidence. -/
def terminal {capability : Capability spec}
    (result : ExecutionResult spec capability) : Terminal :=
  result.stage.added.terminal

/-- Terminal-indexed evidence retained by the single ledger extension. -/
def outcome {capability : Capability spec}
    (result : ExecutionResult spec capability) :
    Outcome capability result.stage.previous result.terminal :=
  result.stage.added.outcome

/-- Observable exact trace. -/
def traceNodes {capability : Capability spec}
    (result : ExecutionResult spec capability) : List NodeId :=
  result.trace.nodes

/-- Actual branch work is bounded by the complete local schedule. -/
theorem checks_le_limit {capability : Capability spec}
    (result : ExecutionResult spec capability) :
    result.checks <= localCheckBound
      (capability.demandsAt result.stage.previous)
      (capability.payersAt result.stage.previous) := by
  rw [result.checks_eq]
  exact outcomeChecks_le_limit result.stage.added.outcome

/-- Every execution satisfies the capability's declared polynomial envelope. -/
theorem checks_le_polynomial {capability : Capability spec}
    (result : ExecutionResult spec capability) :
    result.checks <= capability.workCoefficient *
      (capability.inputSize result.stage.previous + 1) ^
        capability.workDegree :=
  result.checks_le_limit.trans (capability.workBound result.stage.previous)

end ExecutionResult

/-- Execute CT4 on one literal incoming accumulated ledger. -/
def run (spec : Spec.{uPrevious, uDemand, uPayer} Previous)
    (capability : Capability spec) (previous : Previous) :
    ExecutionResult spec capability :=
  let routed := routeReference capability previous
  {
    stage := Core.Residual.Ledger.extend previous routed
    trace := traceOfRouted routed
    checks := outcomeChecks routed.outcome
    checks_eq := rfl
  }

@[simp] theorem run_previous
    (spec : Spec.{uPrevious, uDemand, uPayer} Previous)
    (capability : Capability spec) (previous : Previous) :
    (run spec capability previous).stage.previous = previous :=
  rfl

end Hypostructure.CT4
