import Hypostructure.Core.Coordinate.Transport
import Hypostructure.PDE.Representation

/-!
# PDE coordinate interfaces

Primitive coordinate families return realized maps.  They become primitives
of `Core.CoordinateSystem`; Core owns identity paths, composition, execution,
and composite transport.
-/

namespace Hypostructure.PDE

universe u

/-- A target-independent map between two represented local equations. -/
structure CoordinateMap (M : LocalModel.{u})
    (source target : M.atlas.Window) where
  transform : M.atlas.LocalObject source -> M.atlas.LocalObject target
  transformEquation : forall {object : M.atlas.LocalObject source},
    M.equation.EquationData source object ->
      M.equation.EquationData target (transform object)
  preservesEquation : forall {object : M.atlas.LocalObject source}
      (data : M.equation.EquationData source object),
    M.equation.satisfies data ->
      M.equation.satisfies (transformEquation data)

/-- A coordinate map together with its ambient realization. -/
structure RealizedCoordinate (M : LocalModel.{u})
    (source target : M.atlas.Window) extends CoordinateMap M source target where
  realize : M.problem.Ambient -> M.problem.Ambient
  realizes : forall G,
    transform (M.atlas.restrict G source) =
      M.atlas.restrict (realize G) target
  preservesBaseline : forall {G}, M.problem.Baseline G ->
    M.problem.Baseline (realize G)

/-- The Core coordinate system generated by PDE realized primitives. -/
def coordinateSystem (M : LocalModel.{u}) : Core.CoordinateSystem M.problem where
  Coordinate := M.atlas.Window
  Object := fun _ => M.problem.Ambient
  realize := fun _ object => object
  Primitive := fun source target => RealizedCoordinate M source target
  act := fun step object => step.realize object

/-- Primitive baseline laws registered once for Core path transport. -/
def primitiveBaselineTransport (M : LocalModel.{u}) :
    Core.PrimitiveBaselineTransport (coordinateSystem M) where
  preserves := fun step _ baseline => step.preservesBaseline baseline

/-- Restriction is the canonical realized coordinate for a nested window. -/
def restrictionCoordinate (M : LocalModel.{u}) {small large : M.atlas.Window}
    (h : M.atlas.nested small large) : RealizedCoordinate M large small where
  transform := M.atlas.restrictLocal h
  transformEquation := M.equation.restrictEquation h
  preservesEquation := M.equation.restrict_satisfies h
  realize := id
  realizes := fun G => M.atlas.restrict_global G h
  preservesBaseline := fun hG => hG

/-- Optional family of recentering coordinates. -/
structure RecenteringInterface (M : LocalModel.{u}) where
  Shift : Type u
  targetWindow : Shift -> M.atlas.Window -> M.atlas.Window
  coordinate : forall (shift : Shift) (W : M.atlas.Window),
    RealizedCoordinate M W (targetWindow shift W)

/-- Optional family of rescaling coordinates.  Admissibility may be encoded in `Scale`. -/
structure RescalingInterface (M : LocalModel.{u}) where
  Scale : Type u
  targetWindow : Scale -> M.atlas.Window -> M.atlas.Window
  coordinate : forall (scale : Scale) (W : M.atlas.Window),
    RealizedCoordinate M W (targetWindow scale W)

/-- Optional normalization or gauge action compatible with representation semantics. -/
structure GaugeInterface (M : LocalModel.{u})
    (S : RepresentationSemantics M.problem) where
  Gauge : Type u
  coordinate : forall (_gauge : Gauge) (W : M.atlas.Window),
    RealizedCoordinate M W W
  equivalent_realize : forall (gauge : Gauge) (W : M.atlas.Window)
      (G : M.problem.Ambient),
    S.equivalent ((coordinate gauge W).realize G) G

/-- A quotient projection that identifies exactly the registered representations. -/
structure RepresentationQuotient (M : LocalModel.{u})
    (S : RepresentationSemantics M.problem) where
  Quotient : Type u
  project : M.problem.Ambient -> Quotient
  project_eq_iff : forall {G H}, project G = project H <-> S.equivalent G H

end Hypostructure.PDE
