import Hypostructure.CT15.Capability
import Hypostructure.Core.Finite.Search

/-!
# CT15 generated states

Every state is indexed by the literal predecessor and the schedule retrieved
from it.  Full rank means full rank on that exact schedule, with no assertion
about coordinates outside the residual-owned family.
-/

namespace Hypostructure.CT15

universe uPrevious uCoordinate

variable {Previous : Type uPrevious}
  {spec : Spec.{uPrevious, uCoordinate} Previous}

/-- One coordinate contributes one rank unit exactly when it is independent
of the target. -/
def rankContribution (capability : Capability spec) (previous : Previous)
    (coordinate : spec.Coordinate previous) : Nat :=
  match capability.targetDependentDecidable previous coordinate with
  | .isTrue _ => 0
  | .isFalse _ => 1

/-- Exact target-relative rank on the queried coordinate schedule. -/
def computedRank (capability : Capability spec) (previous : Previous) : Nat :=
  ((capability.coordinatesAt previous).values.map
    (rankContribution capability previous)).sum

/-- Literal full rank of the queried coordinate schedule. -/
def targetRank (capability : Capability spec) (previous : Previous) : Nat :=
  (capability.coordinatesAt previous).card

/-- Framework-computed rank with its defining equality retained. -/
structure RankState (capability : Capability spec) (previous : Previous) where
  value : Nat
  computed : value = computedRank capability previous

/-- Compute the target-relative rank; no value is accepted from a caller. -/
def computeRank (capability : Capability spec) (previous : Previous) :
    RankState capability previous where
  value := computedRank capability previous
  computed := rfl

/-- First target-dependent coordinate in exact schedule order. -/
abbrev RankDropCertificate (capability : Capability spec)
    (previous : Previous) :=
  Core.Finite.Search.IndexedHit (capability.coordinatesAt previous)
    (spec.TargetDependent previous)

/-- Exhaustive target independence at every index of the exact schedule. -/
abbrev ExhaustiveIndependence (capability : Capability spec)
    (previous : Previous) :=
  Core.Finite.Search.Avoids (capability.coordinatesAt previous)
    (spec.TargetDependent previous)

/-- Full-rank state generated from exhaustive first-drop failure. -/
structure FullRankState (capability : Capability spec) (previous : Previous)
    (rank : RankState capability previous) : Prop where
  independence : ExhaustiveIndependence capability previous
  full : rank.value = targetRank capability previous

/-- Canonical ordered charge entries on the residual-owned coordinates. -/
def ledgerEntries (capability : Capability spec) (previous : Previous) :
    List (spec.Coordinate previous × Nat) :=
  (capability.coordinatesAt previous).values.map fun coordinate =>
    (coordinate, spec.charge previous coordinate)

/-- Exact total of the canonical charge ledger. -/
def ledgerTotal (capability : Capability spec) (previous : Previous) : Nat :=
  (ledgerEntries capability previous).map Prod.snd |>.sum

/-- Full-rank charge ledger generated by CT15. -/
structure ChargeLedger (capability : Capability spec) (previous : Previous)
    {rank : RankState capability previous}
    (full : FullRankState capability previous rank) where
  entries : List (spec.Coordinate previous × Nat)
  entries_exact : entries = ledgerEntries capability previous
  total : Nat
  total_exact : total = ledgerTotal capability previous

/-- Build the unique canonical full-rank ledger. -/
def buildLedger (capability : Capability spec) (previous : Previous)
    {rank : RankState capability previous}
    (full : FullRankState capability previous rank) :
    ChargeLedger capability previous full where
  entries := ledgerEntries capability previous
  entries_exact := rfl
  total := ledgerTotal capability previous
  total_exact := rfl

/-- C4 is the exact arithmetic overload of the generated ledger. -/
abbrev C4Certificate (capability : Capability spec) (previous : Previous)
    {rank : RankState capability previous}
    {full : FullRankState capability previous rank}
    (ledger : ChargeLedger capability previous full) : Prop :=
  spec.capacity previous < ledger.total

/-- Reusable full-rank residual when the generated ledger fits capacity. -/
abbrev FullRankLedgerResidual (capability : Capability spec)
    (previous : Previous)
    {rank : RankState capability previous}
    {full : FullRankState capability previous rank}
    (ledger : ChargeLedger capability previous full) : Prop :=
  ledger.total <= spec.capacity previous

end Hypostructure.CT15
