import StructuralExhaustion.Core.FiniteSearch

namespace StructuralExhaustion.Core.FiniteProducedSupportLedger

universe uOccurrence uEntry uVertex

/-!
# Append-only ledgers of actually produced supports

This is the minimal connector between branch-local handoff producers and a
later first-entry test.  It records exactly the supplied production events in
order.  It makes no support-coverage claim and never manufactures an absent
event.
-/

structure Ledger (Entry : Type uEntry) (Vertex : Type uVertex) where
  entries : List Entry
  vertexDecEq : DecidableEq Vertex
  support : Entry → Finset Vertex

namespace Ledger

variable {Entry : Type uEntry} {Vertex : Type uVertex}
variable (ledger : Ledger Entry Vertex)

def empty (vertexDecEq : DecidableEq Vertex)
    (support : Entry → Finset Vertex) : Ledger Entry Vertex where
  entries := []
  vertexDecEq := vertexDecEq
  support := support

/-- Append one exact producer output.  Existing entries and their order are
preserved definitionally. -/
def record (entry : Entry) : Ledger Entry Vertex where
  entries := ledger.entries ++ [entry]
  vertexDecEq := ledger.vertexDecEq
  support := ledger.support

@[simp] theorem record_entries (entry : Entry) :
    (ledger.record entry).entries = ledger.entries ++ [entry] := rfl

theorem entries_prefix_record (entry : Entry) :
    ledger.entries <+: (ledger.record entry).entries := by
  exact List.prefix_append _ _

theorem recorded_mem (entry : Entry) :
    entry ∈ (ledger.record entry).entries := by simp

def Meets (vertex : Vertex) (entry : Entry) : Prop :=
  vertex ∈ ledger.support entry

noncomputable def meetsDecidable (vertex : Vertex) (entry : Entry) :
    Decidable (ledger.Meets vertex entry) := by
  letI : DecidableEq Vertex := ledger.vertexDecEq
  unfold Meets
  infer_instance

noncomputable def recognize (vertex : Vertex) :=
  Core.FiniteSearch.onList ledger.entries (ledger.Meets vertex)
    (ledger.meetsDecidable vertex)

theorem firstHit_exact
    (vertex : Vertex)
    (hit : Core.FiniteSearch.FirstHit ledger.entries (ledger.Meets vertex)) :
    hit.value ∈ ledger.entries ∧ vertex ∈ ledger.support hit.value ∧
      ∀ entry ∈ hit.before, vertex ∉ ledger.support entry :=
  ⟨hit.member, hit.holds, hit.beforeAbsent⟩

noncomputable def checks : Nat := ledger.entries.length

theorem record_checks (entry : Entry) :
    (ledger.record entry).checks = ledger.checks + 1 := by
  simp [checks, record]

/-- Heterogeneous union of two exact producer ledgers.  The left ledger keeps
its order, followed by the right ledger's order; no event is synthesized. -/
def sum {Other : Type*}
    (other : Ledger Other Vertex) : Ledger (Sum Entry Other) Vertex where
  entries := ledger.entries.map Sum.inl ++ other.entries.map Sum.inr
  vertexDecEq := ledger.vertexDecEq
  support
    | .inl entry => ledger.support entry
    | .inr entry => other.support entry

@[simp] theorem sum_entries {Other : Type*}
    (other : Ledger Other Vertex) :
    (ledger.sum other).entries =
      ledger.entries.map Sum.inl ++ other.entries.map Sum.inr := rfl

theorem left_mem_sum {Other : Type*}
    (other : Ledger Other Vertex) {entry : Entry}
    (member : entry ∈ ledger.entries) :
    Sum.inl entry ∈ (ledger.sum other).entries := by
  simp [sum, member]

theorem right_mem_sum {Other : Type*}
    (other : Ledger Other Vertex) {entry : Other}
    (member : entry ∈ other.entries) :
    Sum.inr entry ∈ (ledger.sum other).entries := by
  simp [sum, member]

theorem sum_checks {Other : Type*}
    (other : Ledger Other Vertex) :
    (ledger.sum other).checks = ledger.checks + other.checks := by
  simp [checks, sum]

end Ledger

/-! ## Finite schedules of producer occurrences -/

/-- A finite schedule of actual producer occurrences.  `Occurrence` is kept
separate from `Entry`: two different production steps may emit propositionally
or definitionally equal entries, and both steps must remain visible to later
first-entry scans. -/
structure OccurrenceSchedule (Entry : Type uEntry) where
  Occurrence : Type uOccurrence
  occurrences : FinEnum Occurrence
  event : Occurrence → Entry

namespace OccurrenceSchedule

variable {Entry : Type uEntry} {Vertex : Type uVertex}

/-- The exact append-only ledger generated by a finite occurrence schedule.
The support function is supplied once for the entry type; no support is
deduplicated and no ambient object is searched. -/
noncomputable def ledger
    (schedule : OccurrenceSchedule.{uOccurrence, uEntry} Entry)
    (vertexDecEq : DecidableEq Vertex)
    (support : Entry → Finset Vertex) : Ledger Entry Vertex where
  entries := schedule.occurrences.orderedValues.map schedule.event
  vertexDecEq := vertexDecEq
  support := support

theorem occurrence_mem
    (schedule : OccurrenceSchedule.{uOccurrence, uEntry} Entry)
    (vertexDecEq : DecidableEq Vertex)
    (support : Entry → Finset Vertex)
    (occurrence : schedule.Occurrence) :
    schedule.event occurrence ∈
      (schedule.ledger vertexDecEq support).entries := by
  exact List.mem_map_of_mem
    (schedule.occurrences.mem_orderedValues occurrence)

@[simp] theorem ledger_entries
    (schedule : OccurrenceSchedule.{uOccurrence, uEntry} Entry)
    (vertexDecEq : DecidableEq Vertex)
    (support : Entry → Finset Vertex) :
    (schedule.ledger vertexDecEq support).entries =
      schedule.occurrences.orderedValues.map schedule.event :=
  rfl

/-- A single actual producer output, represented by one occurrence rather
than by a deduplicated set of entries. -/
noncomputable def singleton (entry : Entry) :
    OccurrenceSchedule.{0, uEntry} Entry where
  Occurrence := PUnit
  occurrences := inferInstance
  event := fun _ => entry

/-- Concatenate two occurrence schedules.  The sum tag preserves which
producer occurrence emitted an entry even when the emitted entries are equal.
The inherited `FinEnum (Sum _ _)` order scans the left schedule before the
right schedule. -/
noncomputable def append
    (left : OccurrenceSchedule.{uOccurrence, uEntry} Entry)
    (right : OccurrenceSchedule.{uOccurrence, uEntry} Entry) :
    OccurrenceSchedule.{uOccurrence, uEntry} Entry where
  Occurrence := Sum left.Occurrence right.Occurrence
  occurrences := by
    letI : FinEnum left.Occurrence := left.occurrences
    letI : FinEnum right.Occurrence := right.occurrences
    infer_instance
  event
    | .inl occurrence => left.event occurrence
    | .inr occurrence => right.event occurrence

@[simp] theorem append_event_inl
    (left right : OccurrenceSchedule.{uOccurrence, uEntry} Entry)
    (occurrence : left.Occurrence) :
    (left.append right).event (.inl occurrence) = left.event occurrence :=
  rfl

@[simp] theorem append_event_inr
    (left right : OccurrenceSchedule.{uOccurrence, uEntry} Entry)
    (occurrence : right.Occurrence) :
    (left.append right).event (.inr occurrence) = right.event occurrence :=
  rfl

end OccurrenceSchedule

end StructuralExhaustion.Core.FiniteProducedSupportLedger
