import StructuralExhaustion.CT2.DeletionClosure
import StructuralExhaustion.CT2.LocalDeletion
import StructuralExhaustion.CT2.CertifiedReduction

namespace StructuralExhaustion.CT2

/-! Public automation-first CT2 surface: capability metadata, node contracts,
residual contracts, and execution/verification syntax. -/

/-- Lean-side capability manifest used by generated automation reports. -/
def capabilityContract : Core.CapabilityContract where
  capabilityId := "StructuralExhaustion.CT2.reference"
  tacticId := "CT2"
  requiredDefinitions := [
    ⟨"StructuralExhaustion.CT2.PieceSystem.Piece", .userDefinition⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.pieces", .userFiniteEnumeration⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.Proper", .userDefinition⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.Admissible", .userDefinition⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.properDecidable", .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.admissibleDecidable", .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.InterfaceSystem.Interface", .userDefinition⟩,
    ⟨"StructuralExhaustion.CT2.InterfaceSystem.interface", .userOperator⟩,
    ⟨"StructuralExhaustion.CT2.ContextSystem.AbstractPiece", .userDefinition⟩,
    ⟨"StructuralExhaustion.CT2.ContextSystem.Context", .userDefinition⟩,
    ⟨"StructuralExhaustion.CT2.ContextSystem.contexts", .userFiniteEnumeration⟩,
    ⟨"StructuralExhaustion.CT2.ContextSystem.glue", .userOperator⟩,
    ⟨"StructuralExhaustion.CT2.ContextSystem.abstract", .userOperator⟩,
    ⟨"StructuralExhaustion.CT2.ContextSystem.currentContext", .userOperator⟩,
    ⟨"StructuralExhaustion.CT2.ContextSystem.reconstruct", .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.Observable.baselineDecidable", .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.Observable.targetDecidable", .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.ReductionOps.delete", .userOperator⟩,
    ⟨"StructuralExhaustion.CT2.ReplacementSystem.Candidate", .userDefinition⟩,
    ⟨"StructuralExhaustion.CT2.ReplacementSystem.candidates",
      .userFiniteEnumeration⟩,
    ⟨"StructuralExhaustion.CT2.ReplacementSystem.replacement", .userOperator⟩,
    ⟨"StructuralExhaustion.CT2.ReplacementSystem.decreases", .instanceBridge⟩
  ]
  requiredInstances := [
    "StructuralExhaustion.CT2.PieceSystem.properDecidable",
    "StructuralExhaustion.CT2.PieceSystem.admissibleDecidable",
    "StructuralExhaustion.CT2.ContextSystem.reconstruct",
    "StructuralExhaustion.CT2.Observable.baselineDecidable",
    "StructuralExhaustion.CT2.Observable.targetDecidable",
    "StructuralExhaustion.CT2.ReplacementSystem.decreases"
  ]
  derivedOperations := [
    "StructuralExhaustion.CT2.PieceSystem.discover",
    "StructuralExhaustion.CT2.Observable.observe",
    "StructuralExhaustion.CT2.ReplacementSystem.asSmaller",
    "StructuralExhaustion.CT2.Capability.deletionOnly",
    "StructuralExhaustion.CT2.sourceObject",
    "StructuralExhaustion.CT2.replacementObject",
    "StructuralExhaustion.CT2.sourceObservation",
    "StructuralExhaustion.CT2.replacementObservation",
    "StructuralExhaustion.CT2.analyzeDeletion",
    "StructuralExhaustion.CT2.analyzeCandidate",
    "StructuralExhaustion.CT2.analyzeReplacements",
    "StructuralExhaustion.CT2.runReference",
    "StructuralExhaustion.CT2.run_verified",
    "StructuralExhaustion.CT2.run_total",
    "StructuralExhaustion.CT2.run_deterministic",
    "StructuralExhaustion.CT2.DeletionClosureRule.witness",
    "StructuralExhaustion.CT2.DeletionClosureRule.analyzeDeletion_closes",
    "StructuralExhaustion.CT2.DeletionClosureRule.run_terminal_deletionC2",
    "StructuralExhaustion.CT2.DeletionClosureRule.run_trace_deletionC2",
    "StructuralExhaustion.CT2.DeletionC2Run",
    "StructuralExhaustion.CT2.DeletionC2Run.witness",
    "StructuralExhaustion.CT2.DeletionClosureRule.runDeletionC2",
    "StructuralExhaustion.CT2.DeletionClosureRule.run_closes",
    "StructuralExhaustion.CT2.DeletionClosureRule.discover_disabled",
    "StructuralExhaustion.CT2.DeletionClosureRule.notProper"
  ]

/-- Minimal author contract for a deletion-only CT2 closure.  Unit
interfaces, the dummy identity context, and the empty replacement universe
are generated by `Capability.deletionOnly`. -/
def deletionOnlyCapabilityProfile : Core.CapabilityProfile where
  capabilityId := "StructuralExhaustion.CT2.profile.deletionOnly"
  tacticId := "CT2"
  requiredDefinitions := [
    ⟨"StructuralExhaustion.CT2.PieceSystem.Piece", .userDefinition⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.pieces", .userFiniteEnumeration⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.Proper", .userDefinition⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.Admissible", .userDefinition⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.properDecidable", .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.admissibleDecidable",
      .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.Observable.baselineDecidable", .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.Observable.targetDecidable", .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.ReductionOps.delete", .userOperator⟩,
    ⟨"StructuralExhaustion.CT2.DeletionClosureRule.preservesBaseline",
      .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.DeletionClosureRule.targetMonotone",
      .instanceBridge⟩
  ]
  requiredInstances := [
    "StructuralExhaustion.CT2.PieceSystem.properDecidable",
    "StructuralExhaustion.CT2.PieceSystem.admissibleDecidable",
    "StructuralExhaustion.CT2.Observable.baselineDecidable",
    "StructuralExhaustion.CT2.Observable.targetDecidable",
    "StructuralExhaustion.CT2.DeletionClosureRule.preservesBaseline",
    "StructuralExhaustion.CT2.DeletionClosureRule.targetMonotone"
  ]
  derivedOperations := [
    "StructuralExhaustion.CT2.Capability.deletionOnly",
    "StructuralExhaustion.CT2.DeletionClosureRule.witness",
    "StructuralExhaustion.CT2.DeletionClosureRule.analyzeDeletion_closes",
    "StructuralExhaustion.CT2.DeletionClosureRule.run_terminal_deletionC2",
    "StructuralExhaustion.CT2.DeletionClosureRule.run_trace_deletionC2",
    "StructuralExhaustion.CT2.DeletionClosureRule.runDeletionC2",
    "StructuralExhaustion.CT2.DeletionClosureRule.run_closes",
    "StructuralExhaustion.CT2.DeletionClosureRule.discover_disabled",
    "StructuralExhaustion.CT2.DeletionClosureRule.notProper"
  ]

/-- Minimal author contract for target-decision-free local deletion.  The
framework owns eligible-piece discovery, the typed deletion path, its
constant check budget, and the CT1-avoidance route. -/
def localDeletionCapabilityProfile : Core.CapabilityProfile where
  capabilityId := "StructuralExhaustion.CT2.profile.localDeletion"
  tacticId := "CT2"
  requiredDefinitions := [
    ⟨"StructuralExhaustion.CT2.PieceSystem.Piece", .userDefinition⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.pieces", .userFiniteEnumeration⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.Proper", .userDefinition⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.Admissible", .userDefinition⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.properDecidable", .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.PieceSystem.admissibleDecidable",
      .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.ReductionOps.delete", .userOperator⟩,
    ⟨"StructuralExhaustion.CT2.LocalDeletionClosureRule.preservesBaseline",
      .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.LocalDeletionClosureRule.targetMonotone",
      .instanceBridge⟩
  ]
  requiredInstances := [
    "StructuralExhaustion.CT2.PieceSystem.properDecidable",
    "StructuralExhaustion.CT2.PieceSystem.admissibleDecidable",
    "StructuralExhaustion.CT2.LocalDeletionClosureRule.preservesBaseline",
    "StructuralExhaustion.CT2.LocalDeletionClosureRule.targetMonotone"
  ]
  derivedOperations := [
    "StructuralExhaustion.CT2.LocalDeletionCapability.tacticInterface",
    "StructuralExhaustion.CT2.LocalDeletionCapability.discover",
    "StructuralExhaustion.CT2.LocalDeletionClosureRule.witness",
    "StructuralExhaustion.CT2.LocalDeletionClosureRule.run",
    "StructuralExhaustion.CT2.LocalDeletionClosureRule.notProper",
    "StructuralExhaustion.CT2.localDeletionBudget",
    "StructuralExhaustion.Routes.CT1ToCT2.LocalDeletion.rule"
  ]

/-- Minimal author contract for a proof-specified smaller object.  The
framework owns the canonical CT2 deletion path, semantic contradiction,
totality theorem, and constant work certificate; no piece or ambient-object
enumeration is requested. -/
def certifiedReductionCapabilityProfile : Core.CapabilityProfile where
  capabilityId := "StructuralExhaustion.CT2.profile.certifiedReduction"
  tacticId := "CT2"
  requiredDefinitions := [
    ⟨"StructuralExhaustion.CT2.CertifiedReductionInput.reduction",
      .userOperator⟩,
    ⟨"StructuralExhaustion.CT2.CertifiedReductionInput.reducedBaseline",
      .instanceBridge⟩,
    ⟨"StructuralExhaustion.CT2.CertifiedReductionInput.targetMonotone",
      .instanceBridge⟩
  ]
  requiredInstances := [
    "StructuralExhaustion.CT2.CertifiedReductionInput.reducedBaseline",
    "StructuralExhaustion.CT2.CertifiedReductionInput.targetMonotone"
  ]
  derivedOperations := [
    "StructuralExhaustion.CT2.certifiedReductionTacticInterface",
    "StructuralExhaustion.CT2.CertifiedReductionInput.witness",
    "StructuralExhaustion.CT2.runCertifiedReduction",
    "StructuralExhaustion.CT2.runCertifiedReduction_terminal",
    "StructuralExhaustion.CT2.runCertifiedReduction_trace",
    "StructuralExhaustion.CT2.runCertifiedReduction_total",
    "StructuralExhaustion.CT2.CertifiedReductionRun.verified",
    "StructuralExhaustion.CT2.certifiedReductionBudget"
  ]

/-- Router-visible CT2 residuals.  Neither residual contains a destination
input or a downstream tactic choice. -/
def residualKindContracts : List Core.ResidualKindContract := [
  {
    residualKindId := "CT2.residual.separatingContext"
    leanType := "StructuralExhaustion.CT2.SeparatingContextResidual"
    semanticFields := [
      ⟨"deletionCritical", "DeletionCriticalState", .derivedByComputation⟩,
      ⟨"candidate", "Candidate sourcePiece", .derivedByGenericSearch⟩,
      ⟨"separator", "ContextSeparator candidate", .derivedByGenericSearch⟩,
      ⟨"replacementTable", "ReplacementTable", .derivedByGenericTheorem⟩
    ]
    inheritedContext := .minimalCounterexampleBranch
  },
  {
    residualKindId := "CT2.residual.criticality"
    leanType := "StructuralExhaustion.CT2.CriticalityResidual"
    semanticFields := [
      ⟨"deletionCritical", "DeletionCriticalState", .derivedByComputation⟩,
      ⟨"replacementTable", "ReplacementTable", .derivedByGenericTheorem⟩,
      ⟨"noCandidate", "∀ candidate, False", .derivedByGenericTheorem⟩
    ]
    inheritedContext := .minimalCounterexampleBranch
  }
]

def residualKindIds : List String :=
  residualKindContracts.map (·.residualKindId)

/-- Per-node automation contracts.  Immediate predecessor evidence is omitted
from these static author-input lists by construction. -/
def nodeAutomationContracts : List Core.NodeAutomationContract := [
  {
    nodeId := "CT2.entry"
    executionClass := .definitional
    authorInputs := []
    derivedInputs := [⟨"input.seed", .derivedFromPredecessor⟩]
    frameworkTheorems := []
    generatedOutputs := [⟨"StructuralExhaustion.CT2.Input", .derivedFromPredecessor⟩]
    manualObligations := []
  },
  {
    nodeId := "CT2.decide.deletion"
    executionClass := .verifiedComputation
    authorInputs := [
      ⟨"StructuralExhaustion.CT2.ReductionOps.delete", .userOperator⟩,
      ⟨"StructuralExhaustion.CT2.Observable.baselineDecidable",
        .instanceBridge⟩,
      ⟨"StructuralExhaustion.CT2.Observable.targetDecidable",
        .instanceBridge⟩
    ]
    derivedInputs := [
      ⟨"StructuralExhaustion.CT2.Input.seed", .derivedFromPredecessor⟩,
      ⟨"StructuralExhaustion.CT2.Observable.observe", .derivedByComputation⟩
    ]
    frameworkTheorems := [
      "StructuralExhaustion.CT2.analyzeDeletion_sound",
      "StructuralExhaustion.Core.SmallerObject.counterexample_impossible"
    ]
    generatedOutputs := [
      ⟨"StructuralExhaustion.CT2.DeletionDecision", .derivedByComputation⟩,
      ⟨"StructuralExhaustion.CT2.DeletionWitness", .derivedByComputation⟩,
      ⟨"StructuralExhaustion.CT2.DeletionCriticalState", .derivedByComputation⟩
    ]
    manualObligations := []
  },
  {
    nodeId := "CT2.search.replacements"
    executionClass := .finiteSearch
    authorInputs := [
      ⟨"StructuralExhaustion.CT2.InterfaceSystem.interface", .userOperator⟩,
      ⟨"StructuralExhaustion.CT2.ContextSystem.contexts",
        .userFiniteEnumeration⟩,
      ⟨"StructuralExhaustion.CT2.ContextSystem.glue", .userOperator⟩,
      ⟨"StructuralExhaustion.CT2.ContextSystem.abstract", .userOperator⟩,
      ⟨"StructuralExhaustion.CT2.ContextSystem.currentContext", .userOperator⟩,
      ⟨"StructuralExhaustion.CT2.ContextSystem.reconstruct", .instanceBridge⟩,
      ⟨"StructuralExhaustion.CT2.Observable.baselineDecidable",
        .instanceBridge⟩,
      ⟨"StructuralExhaustion.CT2.Observable.targetDecidable",
        .instanceBridge⟩,
      ⟨"StructuralExhaustion.CT2.ReplacementSystem.Candidate", .userDefinition⟩,
      ⟨"StructuralExhaustion.CT2.ReplacementSystem.candidates",
        .userFiniteEnumeration⟩,
      ⟨"StructuralExhaustion.CT2.ReplacementSystem.replacement", .userOperator⟩,
      ⟨"StructuralExhaustion.CT2.ReplacementSystem.decreases", .instanceBridge⟩
    ]
    derivedInputs := [
      ⟨"StructuralExhaustion.CT2.DeletionCriticalState",
        .derivedFromPredecessor⟩,
      ⟨"DecidableEq StructuralExhaustion.Core.ExactObservation",
        .typeclassInferred⟩,
      ⟨"StructuralExhaustion.CT2.analyzeCandidate", .derivedByGenericSearch⟩,
      ⟨"StructuralExhaustion.CT2.replacementTable", .derivedByGenericTheorem⟩,
      ⟨"StructuralExhaustion.CT2.ReplacementSystem.asSmaller",
        .derivedDefinitionally⟩
    ]
    frameworkTheorems := [
      "StructuralExhaustion.Core.FiniteSearch.search",
      "StructuralExhaustion.CT2.replacementTable_complete"
    ]
    generatedOutputs := [
      ⟨"StructuralExhaustion.CT2.ReplacementDecision", .derivedByGenericSearch⟩,
      ⟨"StructuralExhaustion.CT2.ReplacementWitness", .derivedByGenericSearch⟩,
      ⟨"StructuralExhaustion.CT2.ReplacementTable", .derivedByGenericTheorem⟩,
      ⟨"StructuralExhaustion.CT2.SeparatingContextResidual",
        .derivedByGenericSearch⟩,
      ⟨"StructuralExhaustion.CT2.CriticalityResidual",
        .derivedByGenericTheorem⟩
    ]
    manualObligations := []
  }
]

syntax (name := ct2Discover)
  "ct2_discover " term " at " term : term
macro_rules
  | `(ct2_discover $capability:term at $ctx:term) =>
      `(StructuralExhaustion.CT2.Capability.discover $capability $ctx)

syntax (name := ct2Execute)
  "ct2_execute " term " at " term " on " term : term
macro_rules
  | `(ct2_execute $capability:term at $ctx:term on $input:term) =>
      `(StructuralExhaustion.CT2.run $capability $ctx $input)

syntax (name := ct2Tactic)
  "ct2 " term " at " term " on " term : tactic
macro_rules
  | `(tactic| ct2 $capability:term at $ctx:term on $input:term) =>
      `(tactic| exact StructuralExhaustion.CT2.run_verified
        $capability $ctx $input)

syntax (name := ct2TotalTactic)
  "ct2_total " term " at " term " on " term : tactic
macro_rules
  | `(tactic| ct2_total $capability:term at $ctx:term on $input:term) =>
      `(tactic| exact StructuralExhaustion.CT2.run_total
        $capability $ctx $input)

end StructuralExhaustion.CT2
