import HypostructureParity.Erdos64EG.Fixtures.K4
import HypostructureParity.Erdos64EG.Node1
import HypostructureParity.Erdos64EG.Node2
import HypostructureParity.Erdos64EG.OfficialStatement
import HypostructureParity.Erdos64EG.TargetAlgebra
