import Hypostructure.CT5.Search

/-!
# CT5 accumulated execution

Core finite search and Core binary decisions choose every branch.  CT5 stores
one private routed value as one extension of the literal incoming ledger.
-/

namespace Hypostructure.CT5

universe uPrevious uSite uWitness uResource

variable {Previous : Type uPrevious}
  {spec : Spec.{uPrevious, uSite, uWitness, uResource} Previous}

/-- Exhaustive CT5 terminals. -/
inductive Terminal where
  | deficit
  | c4
  | chargeLedger
  | aggregate
  deriving DecidableEq, Repr

/-- Audit nodes in the complete reference flow. -/
inductive NodeId where
  | entry
  | deficitSearch
  | ledgerComputation
  | comparison
  | deficitTerminal
  | c4Terminal
  | chargeLedgerTerminal
  | aggregateTerminal
  deriving DecidableEq, Repr

/-- Terminal-indexed evidence generated by framework scans and decisions. -/
inductive Outcome (capability : Capability spec) (previous : Previous) :
    Terminal -> Type _ where
  | deficit (residual : LocalDeficitResidual capability previous) :
      Outcome capability previous .deficit
  | c4 (certificate : C4Certificate capability previous) :
      Outcome capability previous .c4
  | chargeLedger (residual : ChargeLedgerResidual capability previous) :
      Outcome capability previous .chargeLedger
  | aggregate (residual : AggregateResidual capability previous) :
      Outcome capability previous .aggregate

/-- Typed trace fixed by a semantic terminal. -/
inductive Trace : Terminal -> Type where
  | deficit : Trace .deficit
  | c4 : Trace .c4
  | chargeLedger : Trace .chargeLedger
  | aggregate : Trace .aggregate

namespace Trace

def nodes : {terminal : Terminal} -> Trace terminal -> List NodeId
  | .deficit, .deficit =>
      [.entry, .deficitSearch, .deficitTerminal]
  | .c4, .c4 =>
      [.entry, .deficitSearch, .ledgerComputation, .comparison, .c4Terminal]
  | .chargeLedger, .chargeLedger =>
      [.entry, .deficitSearch, .ledgerComputation, .comparison,
        .chargeLedgerTerminal]
  | .aggregate, .aggregate =>
      [.entry, .deficitSearch, .ledgerComputation, .comparison,
        .aggregateTerminal]

def expectedNodes : Terminal -> List NodeId
  | .deficit => [.entry, .deficitSearch, .deficitTerminal]
  | .c4 =>
      [.entry, .deficitSearch, .ledgerComputation, .comparison, .c4Terminal]
  | .chargeLedger =>
      [.entry, .deficitSearch, .ledgerComputation, .comparison,
        .chargeLedgerTerminal]
  | .aggregate =>
      [.entry, .deficitSearch, .ledgerComputation, .comparison,
        .aggregateTerminal]

theorem nodes_eq_expected : {terminal : Terminal} ->
    (trace : Trace terminal) -> trace.nodes = expectedNodes terminal
  | .deficit, .deficit => rfl
  | .c4, .c4 => rfl
  | .chargeLedger, .chargeLedger => rfl
  | .aggregate, .aggregate => rfl

end Trace

/-- CT5-routed evidence.  The private constructor prevents callers from
selecting a terminal or pairing it with unrelated evidence. -/
structure Routed (capability : Capability spec) (previous : Previous) where
  private mk ::
  terminal : Terminal
  outcome : Outcome capability previous terminal

/-- Execute the fixed-priority CT5 route using only Core branch constructors. -/
def routeReference (capability : Capability spec) (previous : Previous) :
    Routed capability previous :=
  let deficit := routeDeficit capability previous
  match deficit.added with
  | .yesBranch hasDeficit =>
      .mk .deficit (.deficit
        (deficit.previous.hitOfHasHit hasDeficit))
  | .noBranch deficitFree =>
      let ledger := computeLedger capability previous deficitFree
      let required := routeRequired capability previous ledger
      match required.added with
      | .noBranch capacityFailure =>
          .mk .c4 (.c4 (C4Certificate.ofCapacityFailure ledger
            capacityFailure))
      | .yesBranch requiredBound =>
          let capacity := routeCapacity capability previous ledger
          match capacity.added with
          | .yesBranch totalBound =>
              .mk .chargeLedger (.chargeLedger
                (ChargeLedgerResidual.ofBound ledger totalBound))
          | .noBranch capacityFailure =>
              .mk .aggregate (.aggregate
                (AggregateResidual.ofCapacityFailure ledger requiredBound
                  capacityFailure))

/-- Unique typed trace derived from generated outcome evidence. -/
def traceOfOutcome {capability : Capability spec} {previous : Previous}
    {terminal : Terminal} (outcome : Outcome capability previous terminal) :
    Trace terminal := by
  cases outcome with
  | deficit _ => exact .deficit
  | c4 _ => exact .c4
  | chargeLedger _ => exact .chargeLedger
  | aggregate _ => exact .aggregate

def traceOfRouted {capability : Capability spec} {previous : Previous}
    (routed : Routed capability previous) : Trace routed.terminal :=
  traceOfOutcome routed.outcome

/-- Exact primitive inspections charged by the prescribed reference flow. -/
def outcomeChecks {capability : Capability spec} {previous : Previous} :
    {terminal : Terminal} -> Outcome capability previous terminal -> Nat
  | .deficit, .deficit residual =>
      supportPassChecks capability previous + residual.index.1 + 1
  | .c4, .c4 _ =>
      supportPassChecks capability previous +
        2 * (capability.sitesAt previous).card + 1
  | .chargeLedger, .chargeLedger _ =>
      supportPassChecks capability previous +
        2 * (capability.sitesAt previous).card + 2
  | .aggregate, .aggregate _ =>
      supportPassChecks capability previous +
        2 * (capability.sitesAt previous).card + 2

/-- Branch-exact work never exceeds the complete CT5 schedule. -/
theorem outcomeChecks_le_limit {capability : Capability spec}
    {previous : Previous} {terminal : Terminal}
    (outcome : Outcome capability previous terminal) :
    outcomeChecks outcome <= localCheckBound (capability.familyAt previous) := by
  have supportBound := supportPassChecks_le_witnessCount capability previous
  cases outcome with
  | deficit residual =>
      have siteBound : residual.index.1 + 1 <=
          (capability.sitesAt previous).card :=
        Nat.succ_le_iff.mpr residual.index.isLt
      simp only [outcomeChecks, localCheckBound]
      change supportPassChecks capability previous + residual.index.1 + 1 <=
        capability.witnessCount previous +
          2 * (capability.sitesAt previous).card + 2
      omega
  | c4 _ =>
      simp only [outcomeChecks, localCheckBound]
      change supportPassChecks capability previous +
          2 * (capability.sitesAt previous).card + 1 <=
        capability.witnessCount previous +
          2 * (capability.sitesAt previous).card + 2
      omega
  | chargeLedger _ =>
      simp only [outcomeChecks, localCheckBound]
      change supportPassChecks capability previous +
          2 * (capability.sitesAt previous).card + 2 <=
        capability.witnessCount previous +
          2 * (capability.sitesAt previous).card + 2
      omega
  | aggregate _ =>
      simp only [outcomeChecks, localCheckBound]
      change supportPassChecks capability previous +
          2 * (capability.sitesAt previous).card + 2 <=
        capability.witnessCount previous +
          2 * (capability.sitesAt previous).card + 2
      omega

/-- One CT5 execution is one extension of the literal incoming ledger. -/
abbrev Stage (spec : Spec.{uPrevious, uSite, uWitness, uResource} Previous)
    (capability : Capability spec) :=
  Core.Residual.Ledger.Extension Previous fun previous =>
    Routed capability previous

/-- Closed CT5 execution result with a private constructor. -/
structure ExecutionResult
    (spec : Spec.{uPrevious, uSite, uWitness, uResource} Previous)
    (capability : Capability spec) where
  private mk ::
  stage : Stage spec capability
  trace : Trace stage.added.terminal
  checks : Nat
  checks_eq : checks = outcomeChecks stage.added.outcome

namespace ExecutionResult

def terminal {capability : Capability spec}
    (result : ExecutionResult spec capability) : Terminal :=
  result.stage.added.terminal

def outcome {capability : Capability spec}
    (result : ExecutionResult spec capability) :
    Outcome capability result.stage.previous result.terminal :=
  result.stage.added.outcome

def traceNodes {capability : Capability spec}
    (result : ExecutionResult spec capability) : List NodeId :=
  result.trace.nodes

theorem checks_le_limit {capability : Capability spec}
    (result : ExecutionResult spec capability) :
    result.checks <= localCheckBound
      (capability.familyAt result.stage.previous) := by
  rw [result.checks_eq]
  exact outcomeChecks_le_limit result.stage.added.outcome

theorem checks_le_polynomial {capability : Capability spec}
    (result : ExecutionResult spec capability) :
    result.checks <= (capability.linearWorkBudget).coefficient *
      ((capability.linearWorkBudget).size result.stage.previous + 1) ^
        (capability.linearWorkBudget).degree :=
  result.checks_le_limit.trans
    ((capability.linearWorkBudget).bounded result.stage.previous)

end ExecutionResult

/-- Execute CT5 on one literal accumulated predecessor. -/
def run (spec : Spec.{uPrevious, uSite, uWitness, uResource} Previous)
    (capability : Capability spec) (previous : Previous) :
    ExecutionResult spec capability :=
  let routed := routeReference capability previous
  {
    stage := Core.Residual.Ledger.extend previous routed
    trace := traceOfRouted routed
    checks := outcomeChecks routed.outcome
    checks_eq := rfl
  }

@[simp] theorem run_previous
    (spec : Spec.{uPrevious, uSite, uWitness, uResource} Previous)
    (capability : Capability spec) (previous : Previous) :
    (run spec capability previous).stage.previous = previous :=
  rfl

@[simp] theorem run_residual
    {ResidualType : Type*} [Core.Residual.HasResidual Previous ResidualType]
    (spec : Spec.{uPrevious, uSite, uWitness, uResource} Previous)
    (capability : Capability spec) (previous : Previous) :
    Core.Residual.residualOf (run spec capability previous).stage =
      Core.Residual.residualOf previous :=
  rfl

end Hypostructure.CT5
