import Hypostructure.CT5.Capability
import Hypostructure.Core.Finite.Search

/-!
# CT5 generated states

Every search certificate refers to the exact schedule queried from the literal
predecessor.  Ledger entries are computed in site order from canonical first
support certificates; applications never submit a completed account.
-/

namespace Hypostructure.CT5

universe uPrevious uSite uWitness uResource

variable {Previous : Type uPrevious}
  {spec : Spec.{uPrevious, uSite, uWitness, uResource} Previous}

/-- Canonical support scan at one residual-owned site. -/
def supportScan (capability : Capability spec) (previous : Previous)
    (site : spec.Site previous) :
    Core.Finite.Search.Execution (capability.witnessesAt previous site)
      (spec.Supports previous site) :=
  Core.Finite.Search.run (capability.witnessesAt previous site)
    (spec.Supports previous site)
    (capability.supportsDecidable previous site)

/-- First supporting witness in the exact incoming fibre. -/
abbrev SupportCertificate (capability : Capability spec) (previous : Previous)
    (site : spec.Site previous) :=
  Core.Finite.Search.IndexedHit (capability.witnessesAt previous site)
    (spec.Supports previous site)

/-- Exhaustive support failure in the exact incoming fibre. -/
abbrev NoSupportingWitness (capability : Capability spec)
    (previous : Previous) (site : spec.Site previous) :=
  Core.Finite.Search.Avoids (capability.witnessesAt previous site)
    (spec.Supports previous site)

/-- An active scheduled site whose entire incoming witness fibre fails. -/
def DeficitAt (capability : Capability spec) (previous : Previous)
    (site : spec.Site previous) : Prop :=
  spec.Active previous site /\
    NoSupportingWitness capability previous site

/-- Canonical first local deficit in site order. -/
abbrev LocalDeficitResidual (capability : Capability spec)
    (previous : Previous) :=
  Core.Finite.Search.IndexedHit (capability.sitesAt previous)
    (DeficitAt capability previous)

/-- Exhaustive absence of a local deficit on the exact site schedule. -/
abbrev DeficitFreeState (capability : Capability spec)
    (previous : Previous) :=
  Core.Finite.Search.Avoids (capability.sitesAt previous)
    (DeficitAt capability previous)

/-- Deterministic contribution of one scheduled site.

Inactive sites contribute zero.  Active sites contribute through the first
support selected by Core; a missing support contributes zero only as a total
fallback, and `DeficitFreeState` proves that fallback unreachable on the
ledger branch. -/
def contributionAt (capability : Capability spec) (previous : Previous)
    (site : spec.Site previous) : spec.budget.Resource :=
  match capability.activeDecidable previous site with
  | .isFalse _ => spec.budget.zero
  | .isTrue _ =>
      match (supportScan capability previous site).hit? with
      | none => spec.budget.zero
      | some certificate =>
          spec.contribution previous site certificate.value

/-- Site-ordered contribution account generated by CT5. -/
def contributionLedger (capability : Capability spec) (previous : Previous) :
    List spec.budget.Resource :=
  (capability.sitesAt previous).values.map
    (contributionAt capability previous)

/-- Aggregate of the generated site-ordered contribution account. -/
def ledgerTotal (capability : Capability spec) (previous : Previous) :
    spec.budget.Resource :=
  spec.budget.sum (contributionLedger capability previous)

/-- Complete local ledger, generated only after exhaustive deficit exclusion. -/
structure LocalLedgerState (capability : Capability spec)
    (previous : Previous) where
  private mk ::
  deficitFree : DeficitFreeState capability previous
  entries : List spec.budget.Resource
  entries_eq : entries = contributionLedger capability previous
  total : spec.budget.Resource
  total_eq : total = spec.budget.sum entries

/-- Compute the unique account from the deficit-free predecessor state. -/
def computeLedger (capability : Capability spec) (previous : Previous)
    (deficitFree : DeficitFreeState capability previous) :
    LocalLedgerState capability previous :=
  .mk deficitFree (contributionLedger capability previous) rfl
    (ledgerTotal capability previous) rfl

/-- Capacity cannot meet the registered required amount. -/
structure C4Certificate (capability : Capability spec)
    (previous : Previous) where
  private mk ::
  ledger : LocalLedgerState capability previous
  capacityFailure : Not (spec.required previous <= spec.capacity previous)

namespace C4Certificate

def ofCapacityFailure {capability : Capability spec} {previous : Previous}
    (ledger : LocalLedgerState capability previous)
    (failure : Not (spec.required previous <= spec.capacity previous)) :
    C4Certificate capability previous :=
  .mk ledger failure

end C4Certificate

/-- Generated bounded contribution ledger for downstream accounting. -/
structure ChargeLedgerResidual (capability : Capability spec)
    (previous : Previous) where
  private mk ::
  ledger : LocalLedgerState capability previous
  total_le_capacity : ledger.total <= spec.capacity previous

namespace ChargeLedgerResidual

def ofBound {capability : Capability spec} {previous : Previous}
    (ledger : LocalLedgerState capability previous)
    (bounded : ledger.total <= spec.capacity previous) :
    ChargeLedgerResidual capability previous :=
  .mk ledger bounded

end ChargeLedgerResidual

/-- Generated aggregate beyond capacity after the required amount was shown
affordable. -/
structure AggregateResidual (capability : Capability spec)
    (previous : Previous) where
  private mk ::
  ledger : LocalLedgerState capability previous
  required_le_capacity : spec.required previous <= spec.capacity previous
  capacityFailure : Not (ledger.total <= spec.capacity previous)

namespace AggregateResidual

def ofCapacityFailure {capability : Capability spec} {previous : Previous}
    (ledger : LocalLedgerState capability previous)
    (requiredBound : spec.required previous <= spec.capacity previous)
    (failure : Not (ledger.total <= spec.capacity previous)) :
    AggregateResidual capability previous :=
  .mk ledger requiredBound failure

end AggregateResidual

end Hypostructure.CT5
