import StructuralExhaustion.CT4.Theorems
import StructuralExhaustion.Core.EnumerationCombinators

namespace StructuralExhaustion.CT4

universe uEntry uCarrier uSlot

variable {P : Core.Problem}

/-- Minimal specialization for CT4 uses whose only purpose is to find an
unassigned demand.  Weights, capacities, and the final capacity comparison
are irrelevant on this branch, so the framework supplies them canonically.
The author provides only the two finite universes, eligibility, its decider,
and the fact that one payer cannot serve two different demands. -/
structure FunctionalCardinalityProfile (P : Core.Problem) where
  Demand : Type
  Payer : Type
  Eligible : Input P → Demand → Payer → Prop
  demands : FinEnum Demand
  payers : FinEnum Payer
  eligibleDecidable :
    (input : Input P) → (demand : Demand) → (payer : Payer) →
      Decidable (Eligible input demand payer)
  functional : ∀ input payer demand₁ demand₂,
    Eligible input demand₁ payer → Eligible input demand₂ payer →
      demand₁ = demand₂

namespace FunctionalCardinalityProfile

/-- CT4 specification generated from the minimal functional profile. -/
def spec (profile : FunctionalCardinalityProfile P) : Spec P where
  Demand := profile.Demand
  Payer := profile.Payer
  Eligible := profile.Eligible
  demandWeight := fun _ _ => 0
  capacity := fun _ _ => 0

/-- CT4 capability generated from the minimal functional profile. -/
def capability (profile : FunctionalCardinalityProfile P) :
    Capability profile.spec where
  demands := profile.demands
  payers := profile.payers
  eligibleDecidable := profile.eligibleDecidable
  required := fun _ => 0

/-- Exact CT4 execution generated by the profile. -/
def run (profile : FunctionalCardinalityProfile P) (input : Input P) :=
  CT4.run profile.spec profile.capability input

end FunctionalCardinalityProfile

variable (S : Spec P) (capability : Capability S)
variable (input : Input P)

/-- If each payer can serve at most one demand, a total CT4 assignment
injects the demand universe into the payer universe.  The proof uses only the
two explicit `FinEnum` values carried by the capability. -/
theorem card_demands_le_card_payers_of_total
    (total : TotalAssignmentState S capability input)
    (functional : ∀ payer demand₁ demand₂,
      S.Eligible input demand₁ payer → S.Eligible input demand₂ payer →
        demand₁ = demand₂) :
    capability.demands.card ≤ capability.payers.card := by
  classical
  let assigned : S.Demand → S.Payer := fun demand =>
    (total.total demand).choose
  have assignedEligible : ∀ demand,
      S.Eligible input demand (assigned demand) := by
    intro demand
    exact (total.total demand).choose_spec.2
  have assignedInjective : Function.Injective assigned := by
    intro demand₁ demand₂ equal
    exact functional (assigned demand₁) demand₁ demand₂
      (assignedEligible demand₁) (equal ▸ assignedEligible demand₂)
  let finiteMap : Fin capability.demands.card → Fin capability.payers.card :=
    fun index => capability.payers.equiv
      (assigned (capability.demands.equiv.symm index))
  have finiteMapInjective : Function.Injective finiteMap := by
    intro left right equal
    have payerEqual :
        assigned (capability.demands.equiv.symm left) =
          assigned (capability.demands.equiv.symm right) :=
      capability.payers.equiv.injective equal
    have demandEqual := assignedInjective payerEqual
    simpa [finiteMap] using congrArg capability.demands.equiv demandEqual
  simpa [finiteMap] using Fintype.card_le_of_injective finiteMap finiteMapInjective

/-- Functional eligibility and strictly fewer payers force CT4's exact
reference execution to stop at the missing-payer terminal. -/
theorem run_terminal_eq_missing_of_card_lt
    (functional : ∀ payer demand₁ demand₂,
      S.Eligible input demand₁ payer → S.Eligible input demand₂ payer →
        demand₁ = demand₂)
    (card_lt : capability.payers.card < capability.demands.card) :
    (run S capability input).terminal = .missing := by
  generalize runEqual : run S capability input = result
  cases result with
  | mk terminal path outcome =>
      cases outcome with
      | missing residual => rfl
      | overload residual =>
          exact (Nat.not_le_of_gt card_lt
            (card_demands_le_card_payers_of_total S capability input
              residual.total functional)).elim
      | c4 certificate =>
          exact (Nat.not_le_of_gt card_lt
            (card_demands_le_card_payers_of_total S capability input
              certificate.bounded.total functional)).elim
      | capacity residual =>
          exact (Nat.not_le_of_gt card_lt
            (card_demands_le_card_payers_of_total S capability input
              residual.bounded.total functional)).elim

namespace ExecutionResult

/-- Recover terminal-indexed missing-payer evidence after proving that an
execution reached the missing terminal. -/
def missingResidual (result : ExecutionResult S capability input)
    (terminal : result.terminal = .missing) :
    MissingPayerResidual S input := by
  cases result with
  | mk foundTerminal path outcome =>
      cases outcome with
      | missing residual => exact residual
      | overload _ => cases terminal
      | c4 _ => cases terminal
      | capacity _ => cases terminal

end ExecutionResult

/-- The first missing demand selected by the complete CT4 reference run under
a functional strict-cardinality profile. -/
def missingResidualOfCardLt
    (functional : ∀ payer demand₁ demand₂,
      S.Eligible input demand₁ payer → S.Eligible input demand₂ payer →
        demand₁ = demand₂)
    (card_lt : capability.payers.card < capability.demands.card) :
    MissingPayerResidual S input :=
  ExecutionResult.missingResidual S capability input (run S capability input)
    (run_terminal_eq_missing_of_card_lt S capability input functional card_lt)

namespace FunctionalCardinalityProfile

/-- A strict cardinality gap forces the generated profile run to the missing
terminal. -/
theorem run_terminal_eq_missing (profile : FunctionalCardinalityProfile P)
    (input : Input P) (card_lt : profile.payers.card < profile.demands.card) :
    (profile.run input).terminal = .missing :=
  run_terminal_eq_missing_of_card_lt profile.spec profile.capability input
    (profile.functional input) card_lt

/-- The canonical missing-demand residual generated by the profile. -/
def missingResidual (profile : FunctionalCardinalityProfile P)
    (input : Input P) (card_lt : profile.payers.card < profile.demands.card) :
    MissingPayerResidual profile.spec input :=
  missingResidualOfCardLt profile.spec profile.capability input
    (profile.functional input) card_lt

end FunctionalCardinalityProfile

/-! ## Private-carrier capacity

This profile is the reusable form of the manuscript pattern “each indexed
object selects `k` private carriers, and private carriers of distinct indexed
objects are disjoint”.  Applications expose only the already constructed
finite entry/carrier ledgers and the semantic privacy proofs.  The framework
owns the product-demand enumeration and the global injection/counting step.
-/

structure PrivateCarrierProfile (P : Core.Problem) where
  Entry : Type uEntry
  Carrier : Type uCarrier
  Slot : Type uSlot
  entries : FinEnum Entry
  carriers : FinEnum Carrier
  slots : FinEnum Slot
  Private : Input P → Entry → Carrier → Prop
  chosen : Input P → Entry → Slot → Carrier
  chosen_private : ∀ input entry slot,
    Private input entry (chosen input entry slot)
  chosen_distinct : ∀ input entry,
    Function.Injective (chosen input entry)
  private_owner : ∀ input carrier left right,
    Private input left carrier → Private input right carrier → left = right

namespace PrivateCarrierProfile

variable (profile : PrivateCarrierProfile P)

@[implicit_reducible]
def demands : FinEnum (profile.Entry × profile.Slot) :=
  Core.Enumeration.prod profile.entries profile.slots

/-- The carrier selected for an entry/slot pair. -/
def payer (input : Input P) (demand : profile.Entry × profile.Slot) :
    profile.Carrier :=
  profile.chosen input demand.1 demand.2

/-- Privacy plus within-entry distinctness makes the complete charging map
injective.  No ambient graph or state universe is enumerated. -/
theorem payer_injective (input : Input P) :
    Function.Injective (profile.payer input) := by
  intro left right equal
  have ownerEqual : left.1 = right.1 :=
    profile.private_owner input (profile.payer input left) left.1 right.1
      (profile.chosen_private input left.1 left.2)
      (equal ▸ profile.chosen_private input right.1 right.2)
  cases left with
  | mk leftEntry leftSlot =>
    cases right with
    | mk rightEntry rightSlot =>
      simp only at ownerEqual
      subst rightEntry
      have slotEqual : leftSlot = rightSlot :=
        profile.chosen_distinct input leftEntry equal
      subst rightSlot
      rfl

/-- Exact private-carrier capacity bound.  The left side is the number of
entry/slot demands and the right side is the literal carrier ledger size. -/
theorem slot_mul_entry_le_carrier (input : Input P) :
    profile.entries.card * profile.slots.card ≤ profile.carriers.card := by
  letI : Fintype profile.Entry := @FinEnum.instFintype _ profile.entries
  letI : Fintype profile.Slot := @FinEnum.instFintype _ profile.slots
  letI : Fintype profile.Carrier := @FinEnum.instFintype _ profile.carriers
  have bound : Fintype.card (profile.Entry × profile.Slot) ≤
      Fintype.card profile.Carrier :=
    Fintype.card_le_of_injective (profile.payer input)
      (profile.payer_injective input)
  simpa [FinEnum.card_eq_fintypeCard, Fintype.card_prod] using bound

/-- This capacity theorem performs no search: the application has already
selected the private carriers while building its local ledger. -/
def localCheckCount (_profile : PrivateCarrierProfile P)
    (_input : Input P) : Nat := 0

theorem localCheckCount_polynomial (input : Input P) :
    profile.localCheckCount input ≤
      (profile.entries.card + profile.carriers.card + 1) ^ 1 := by
  simp [localCheckCount]

end PrivateCarrierProfile

end StructuralExhaustion.CT4
