import StructuralExhaustion.CT4.Theorems

namespace StructuralExhaustion.CT4

variable {P : Core.Problem}

/-- Minimal specialization for CT4 uses whose only purpose is to find an
unassigned demand.  Weights, capacities, and the final capacity comparison
are irrelevant on this branch, so the framework supplies them canonically.
The author provides only the two finite universes, eligibility, its decider,
and the fact that one payer cannot serve two different demands. -/
structure FunctionalCardinalityProfile (P : Core.Problem) where
  Demand : Type
  Payer : Type
  Eligible : Input P → Demand → Payer → Prop
  demands : FinEnum Demand
  payers : FinEnum Payer
  eligibleDecidable :
    (input : Input P) → (demand : Demand) → (payer : Payer) →
      Decidable (Eligible input demand payer)
  functional : ∀ input payer demand₁ demand₂,
    Eligible input demand₁ payer → Eligible input demand₂ payer →
      demand₁ = demand₂

namespace FunctionalCardinalityProfile

/-- CT4 specification generated from the minimal functional profile. -/
def spec (profile : FunctionalCardinalityProfile P) : Spec P where
  Demand := profile.Demand
  Payer := profile.Payer
  Eligible := profile.Eligible
  demandWeight := fun _ _ => 0
  capacity := fun _ _ => 0

/-- CT4 capability generated from the minimal functional profile. -/
def capability (profile : FunctionalCardinalityProfile P) :
    Capability profile.spec where
  demands := profile.demands
  payers := profile.payers
  eligibleDecidable := profile.eligibleDecidable
  required := fun _ => 0

/-- Exact CT4 execution generated by the profile. -/
def run (profile : FunctionalCardinalityProfile P) (input : Input P) :=
  CT4.run profile.spec profile.capability input

end FunctionalCardinalityProfile

variable (S : Spec P) (capability : Capability S)
variable (input : Input P)

/-- If each payer can serve at most one demand, a total CT4 assignment
injects the demand universe into the payer universe.  The proof uses only the
two explicit `FinEnum` values carried by the capability. -/
theorem card_demands_le_card_payers_of_total
    (total : TotalAssignmentState S capability input)
    (functional : ∀ payer demand₁ demand₂,
      S.Eligible input demand₁ payer → S.Eligible input demand₂ payer →
        demand₁ = demand₂) :
    capability.demands.card ≤ capability.payers.card := by
  classical
  let assigned : S.Demand → S.Payer := fun demand =>
    (total.total demand).choose
  have assignedEligible : ∀ demand,
      S.Eligible input demand (assigned demand) := by
    intro demand
    exact (total.total demand).choose_spec.2
  have assignedInjective : Function.Injective assigned := by
    intro demand₁ demand₂ equal
    exact functional (assigned demand₁) demand₁ demand₂
      (assignedEligible demand₁) (equal ▸ assignedEligible demand₂)
  let finiteMap : Fin capability.demands.card → Fin capability.payers.card :=
    fun index => capability.payers.equiv
      (assigned (capability.demands.equiv.symm index))
  have finiteMapInjective : Function.Injective finiteMap := by
    intro left right equal
    have payerEqual :
        assigned (capability.demands.equiv.symm left) =
          assigned (capability.demands.equiv.symm right) :=
      capability.payers.equiv.injective equal
    have demandEqual := assignedInjective payerEqual
    simpa [finiteMap] using congrArg capability.demands.equiv demandEqual
  simpa [finiteMap] using Fintype.card_le_of_injective finiteMap finiteMapInjective

/-- Functional eligibility and strictly fewer payers force CT4's exact
reference execution to stop at the missing-payer terminal. -/
theorem run_terminal_eq_missing_of_card_lt
    (functional : ∀ payer demand₁ demand₂,
      S.Eligible input demand₁ payer → S.Eligible input demand₂ payer →
        demand₁ = demand₂)
    (card_lt : capability.payers.card < capability.demands.card) :
    (run S capability input).terminal = .missing := by
  generalize runEqual : run S capability input = result
  cases result with
  | mk terminal path outcome =>
      cases outcome with
      | missing residual => rfl
      | overload residual =>
          exact (Nat.not_le_of_gt card_lt
            (card_demands_le_card_payers_of_total S capability input
              residual.total functional)).elim
      | c4 certificate =>
          exact (Nat.not_le_of_gt card_lt
            (card_demands_le_card_payers_of_total S capability input
              certificate.bounded.total functional)).elim
      | capacity residual =>
          exact (Nat.not_le_of_gt card_lt
            (card_demands_le_card_payers_of_total S capability input
              residual.bounded.total functional)).elim

namespace ExecutionResult

/-- Recover terminal-indexed missing-payer evidence after proving that an
execution reached the missing terminal. -/
def missingResidual (result : ExecutionResult S capability input)
    (terminal : result.terminal = .missing) :
    MissingPayerResidual S input := by
  cases result with
  | mk foundTerminal path outcome =>
      cases outcome with
      | missing residual => exact residual
      | overload _ => cases terminal
      | c4 _ => cases terminal
      | capacity _ => cases terminal

end ExecutionResult

/-- The first missing demand selected by the complete CT4 reference run under
a functional strict-cardinality profile. -/
def missingResidualOfCardLt
    (functional : ∀ payer demand₁ demand₂,
      S.Eligible input demand₁ payer → S.Eligible input demand₂ payer →
        demand₁ = demand₂)
    (card_lt : capability.payers.card < capability.demands.card) :
    MissingPayerResidual S input :=
  ExecutionResult.missingResidual S capability input (run S capability input)
    (run_terminal_eq_missing_of_card_lt S capability input functional card_lt)

namespace FunctionalCardinalityProfile

/-- A strict cardinality gap forces the generated profile run to the missing
terminal. -/
theorem run_terminal_eq_missing (profile : FunctionalCardinalityProfile P)
    (input : Input P) (card_lt : profile.payers.card < profile.demands.card) :
    (profile.run input).terminal = .missing :=
  run_terminal_eq_missing_of_card_lt profile.spec profile.capability input
    (profile.functional input) card_lt

/-- The canonical missing-demand residual generated by the profile. -/
def missingResidual (profile : FunctionalCardinalityProfile P)
    (input : Input P) (card_lt : profile.payers.card < profile.demands.card) :
    MissingPayerResidual profile.spec input :=
  missingResidualOfCardLt profile.spec profile.capability input
    (profile.functional input) card_lt

end FunctionalCardinalityProfile

end StructuralExhaustion.CT4
